### ISSUE TITLE
cluster failing during master node initialization

### ISSUE THREAD

**Issue by hiteshsharma0** [vmware/container-service-extension#1258]
Hello Team,

We are facing some issue with the cluster creation. we are using vcd 10.2, CSE 3.1.0. The cluster creation was working fine when we last checked. here are some logs while creation of the master node. As i mentioned, the master node is sucessfully created and Ip is assigned to it, however the deployment fails while executing the script in the node.  if you can give us some clue to fix it and please let me know if you need more information:-

21-11-17 13:31:42 | vcdbroker:1964 - _wait_for_tools_ready_callback | Request Id: 53a7e09c-5514-4b5a-af08-d22ec81cd9f3 | DEBUG :: waiting for guest tools, status: vm='vim.VirtualMachine:vm-451969', status=guestToolsRunning
21-11-17 13:31:43 | vcdbroker:2019 - _init_cluster | Request Id: 53a7e09c-5514-4b5a-af08-d22ec81cd9f3 | ERROR :: Error executing script in node mstr-iio8: <module 'container_service_extension.exception.exceptions' from '/usr/local/lib/python3.7/site-packages/container_service_extension/exception/exceptions.py'>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/container_service_extension/server/vcdbroker.py", line 2115, in _execute_script_in_nodes
    _wait_until_ready_to_exec(vs, vm, password)
  File "/usr/local/lib/python3.7/site-packages/container_service_extension/server/vcdbroker.py", line 2081, in _wait_until_ready_to_exec
    callback=_wait_for_guest_execution_callback)
  File "/usr/local/lib/python3.7/site-packages/vsphere_guest_run/vsphere.py", line 203, in execute_script_in_guest
    self.upload_file_to_guest(vm, user, password, content, target)
  File "/usr/local/lib/python3.7/site-packages/vsphere_guest_run/vsphere.py", line 147, in upload_file_to_guest
    'Error while uploading file: %s' % resp.status_code)
Exception: Error while uploading file: 504

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/container_service_extension/server/vcdbroker.py", line 2010, in _init_cluster
    node_names=node_names, script=script)
  File "/usr/local/lib/python3.7/site-packages/container_service_extension/server/vcdbroker.py", line 2142, in _execute_script_in_nodes
    raise e.ScriptExecutionError(f"Error executing script in node {node_name}: {str(e)}")  # noqa: E501
container_service_extension.exception.exceptions.ScriptExecutionError: Error executing script in node mstr-iio8: <module 'container_service_extension.exception.exceptions' from '/usr/local/lib/python3.7/site-packages/container_service_extension/exception/exceptions.py'>
21-11-17 13:31:43 | vcdbroker:1045 - _create_cluster_async | Request Id: 53a7e09c-5514-4b5a-af08-d22ec81cd9f3 | DEBUG :: Error creating cluster 'k6-cluster2-aanku'. Deleting cluster (rollback=True)
21-11-17 13:31:44 | vcdbroker:1513 - _delete_vapp | Request Id: 53a7e09c-5514-4b5a-af08-d22ec81cd9f3 | DEBUG :: Deleting vapp k6-cluster2-aanku (vdc: https://ecm001.esa.int/api/vdc/d2c15bdb-fcfa-4356-b1d3-ab2599e80f09)
21-11-17 13:32:11 | vcdbroker:1524 - _delete_vapp | Request Id: 53a7e09c-5514-4b5a-af08-d22ec81cd9f3 | DEBUG :: Deleted vapp k6-cluster2-aanku (vdc: https://ecm001.esa.int/api/vdc/d2c15bdb-fcfa-4356-b1d3-ab2599e80f09)
21-11-17 13:32:11 | vcdbroker:1059 - _create_cluster_async | Request Id: 53a7e09c-5514-4b5a-af08-d22ec81cd9f3 | ERROR :: Error creating cluster 'k6-cluster2-aanku'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/container_service_extension/server/vcdbroker.py", line 2115, in _execute_script_in_nodes
    _wait_until_ready_to_exec(vs, vm, password)
  File "/usr/local/lib/python3.7/site-packages/container_service_extension/server/vcdbroker.py", line 2081, in _wait_until_ready_to_exec
    callback=_wait_for_guest_execution_callback)
  File "/usr/local/lib/python3.7/site-packages/vsphere_guest_run/vsphere.py", line 203, in execute_script_in_guest
    self.upload_file_to_guest(vm, user, password, content, target)
  File "/usr/local/lib/python3.7/site-packages/vsphere_guest_run/vsphere.py", line 147, in upload_file_to_guest
    'Error while uploading file: %s' % resp.status_code)
Exception: Error while uploading file: 504

**Comment by Anirudh9794** [comment]
Hello Hithesh,
How often is this error occurring?
We have observed this error in the past and a retry usually fixes this issue.

**Comment by hiteshsharma0** [comment]
Hello Anirudh,

We are getting this error everytime, we create a cluster. I have retried lot of times.

**Comment by Anirudh9794** [comment]
If this error is occurring with just the worker node, Can you try creating a cluster with 0 worker nodes and later on resize the cluster to add another node.
I think this is caused by vsphere-guest-run library that CSE is using to execute scripts in the vm.

**Comment by hiteshsharma0** [comment]
Thanks for your prompt response, We are getting the initialization error in the master node customization process, particularly mstr.sh script. The only change which we made recently is upgrading the resource vcenter to 7.0u2 and i couldn't find any incompatibility of CSE with vsphere. Everywhere, its mentioned about vcd and other components. Also i feel for most operations, CSE contacts VCD except guest customization. Can you please suggest something?

**Comment by hiteshsharma0** [comment]
I have even tried running cse in non legacy mode, and the upgrade fails with a similar error in the installation logs:-


21-11-18 05:56:11 | configure_cse:1699 - _assign_placement_policies_to_existing_templates | DEBUG :: Assigning placement policies to existing templates.
21-11-18 05:56:11 | configure_cse:1714 - _assign_placement_policies_to_existing_templates | DEBUG :: Processing template ubuntu-16.04_k8-1.20_weave-2.6.5 revision 2
21-11-18 05:56:20 | template_builder:60 - assign_placement_policy_to_template | INFO :: Successfully tagged template ubuntu-16.04_k8-1.20_weave-2.6.5_rev2 with placement policy native.
21-11-18 05:56:20 | configure_cse:1714 - _assign_placement_policies_to_existing_templates | DEBUG :: Processing template ubuntu-16.04_k8-1.19_weave-2.6.5 revision 2
21-11-18 05:56:30 | template_builder:60 - assign_placement_policy_to_template | INFO :: Successfully tagged template ubuntu-16.04_k8-1.19_weave-2.6.5_rev2 with placement policy native.
21-11-18 05:56:30 | configure_cse:1714 - _assign_placement_policies_to_existing_templates | DEBUG :: Processing template ubuntu-16.04_k8-1.18_weave-2.6.5 revision 2
21-11-18 05:56:40 | template_builder:60 - assign_placement_policy_to_template | INFO :: Successfully tagged template ubuntu-16.04_k8-1.18_weave-2.6.5_rev2 with placement policy native.
21-11-18 05:56:40 | configure_cse:2059 - _upgrade_to_cse_3_1_non_legacy | INFO :: Loading all CSE clusters for processing...
21-11-18 05:57:22 | configure_cse:819 - upgrade_cse | ERROR :: CSE Installation Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/container_service_extension/server/vcdbroker.py", line 2126, in _execute_script_in_nodes
    callback=_wait_for_guest_execution_callback)
  File "/usr/local/lib/python3.7/site-packages/vsphere_guest_run/vsphere.py", line 203, in execute_script_in_guest
    self.upload_file_to_guest(vm, user, password, content, target)
  File "/usr/local/lib/python3.7/site-packages/vsphere_guest_run/vsphere.py", line 147, in upload_file_to_guest
    'Error while uploading file: %s' % resp.status_code)
Exception: Error while uploading file: 504

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/container_service_extension/installer/configure_cse.py", line 807, in upgrade_cse
    log_wire=log_wire)
  File "/usr/local/lib/python3.7/site-packages/container_service_extension/installer/configure_cse.py", line 2061, in _upgrade_to_cse_3_1_non_legacy
    clusters = get_all_cse_clusters(client=client, fetch_details=True)
  File "/usr/local/lib/python3.7/site-packages/container_service_extension/server/vcdbroker.py", line 1787, in get_all_clusters
    _update_cluster_dict_with_node_info(client, cluster)
  File "/usr/local/lib/python3.7/site-packages/container_service_extension/server/vcdbroker.py", line 1626, in _update_cluster_dict_with_node_info
    client, node_info['ipAddress'], vapp, vm_name)
  File "/usr/local/lib/python3.7/site-packages/container_service_extension/server/vcdbroker.py", line 1581, in _get_nfs_exports

Can someone please suggest what we can do to fix this issue? or atleast give us a clue why is it failing at vsphere level.

**Comment by hiteshsharma0** [comment]
Hello @Anirudh9794,

We somehow manage to come out of the situation where we were not able to create clusters by upgrading CSE to non legacy mode. we are able to create new clusters now however we are not able to list or manage existing clusters. below is the error which we are received when upgrade script was trying to upgrade the clusters:-

minor_error_code=MinorErrorCode.DEFAULT_ERROR_CODE)container_service_extension.exception.exceptions.DefEntityServiceError: [ 53bf4f8d-636b-42fd-bdf1-59053e2da89d ] This operation is denied.21-11-18 12:36:34 | configure_cse:2406 - _process_non_legacy_clusters | INFO :: Processing cluster 'k6-multienv-name'21-11-18 12:36:34 | configure_cse:2434 - _process_non_legacy_clusters | ERROR :: [ b55e943a-3ec5-481a-b36a-72631b02b58e ] This operation is denied.Traceback (most recent call last):File "/usr/local/lib/python3.7/site-packages/container_service_extension/rde/common/entity_service.py", line 49, in exception_handler_wrapperresult = func(*args, **kwargs)File "/usr/local/lib/python3.7/site-packages/container_service_extension/rde/common/entity_service.py", line 327, in get_entityresource_url_relative_path=f"{CloudApiResource.ENTITIES}/"File "/usr/local/lib/python3.7/site-packages/container_service_extension/lib/cloudapi/cloudapi_client.py", line 134, in do_requestresponse.raise_for_status()File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_statusraise HTTPError(http_error_msg, response=self)requests.exceptions.HTTPError: 403 Client Error: Forbidden for url:https://VCD_URL/cloudapi/1.0.0/entities/7314cf0b-9033-4758-9755-8dcbfb4fc875During handling of the above exception, another exception occurred:

Can you suggest how we can fix this issue so that we can list/manage old native clusters?

**Comment by Anirudh9794** [comment]
Hello Hitesh,
Can you please confirm if the upgrade went through fine without any errors?

If not, im afraid CSE needs to be upgraded to CSE 3.1.1 as there is a bug preventing rerunning CSE upgrade (which usually tries to move all the resources to a state that can be managed by the new CSE)

**Comment by Anirudh9794** [comment]
Hello @hiteshsharma0 ,
Can you confirm if the issue was resolved? 

Thanks,
Aniruddha

**Comment by hiteshsharma0** [comment]
Hello Anirudh,

Thanks for your support. The issue is resolved.
