### ISSUE TITLE
Unable to create TKG or Native clusters

### ISSUE THREAD

**Issue by sreejesh-d** [vmware/container-service-extension#1262]
Hi All,
trust you all doing well.
Create new Native or TKG cluster fails with following error. Tried with System administrator as well as Tenant Org Administrator ( with org admin role which has privileges from ‘Right bundle for Native cluster → cse:nativeCluster entitlement'
am I missing something here?
cse 3.1.1
vcd 10.3.1
![image](https://user-images.githubusercontent.com/21360201/143184144-a4d57aa0-480a-4f2b-a5ae-e1e241f75d6a.png)

This is the response for API call
POST https://<vcd>/api/cse/3.0/clusters

{
	"message": {
		"minor error code": -1,
		"error description": "[ 570a7e09-25b1-477f-bfde-90a205b44beb ] This operation is denied."
	}
}

**Comment by sreejesh-d** [comment]
Errors from CSE logs :

, 'memory': None}, 'nfs': {'count': 0, 'sizingClass': None, 'storageProfile': None}}, 'settings': {'ovdcNetwork': 'Private-Network', 'rollbackOnFailure': True}, 'distribution': {'templateName': 'ubuntu-16.04_k8-1.21_weave-2.8.1', 'templateRevision': 1}}}
21-11-24 07:10:46 | entity_service:56 - exception_handler_wrapper | Request Id: 69c2d64f-9e7c-47fc-a740-b1c1a8ec76ad | ERROR :: [ 177982db-cfca-4687-b13e-88a776179305 ] This operation is denied.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/container_service_extension/rde/common/entity_service.py", line 52, in exception_handler_wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/container_service_extension/rde/common/entity_service.py", line 113, in create_entity
    return_response_headers=is_request_async)
  File "/usr/local/lib/python3.7/site-packages/container_service_extension/lib/cloudapi/cloudapi_client.py", line 139, in do_request
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://<vcd>/cloudapi/1.0.0/entityTypes/urn:vcloud:type:cse:nativeCluster:2.0.0
21-11-24 07:10:46 | request_utils:166 - exception_handler_wrapper | Request Id: 69c2d64f-9e7c-47fc-a740-b1c1a8ec76ad | ERROR :: [ 177982db-cfca-4687-b13e-88a776179305 ] This operation is denied.
21-11-24 07:10:46 | exception_handler:53 - exception_handler_wrapper | Request Id: 69c2d64f-9e7c-47fc-a740-b1c1a8ec76ad | ERROR :: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/container_service_extension/rde/common/entity_service.py", line 52, in exception_handler_wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/container_service_extension/rde/common/entity_service.py", line 113, in create_entity
    return_response_headers=is_request_async)
  File "/usr/local/lib/python3.7/site-packages/container_service_extension/lib/cloudapi/cloudapi_client.py", line 139, in do_request
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://<vcd>/cloudapi/1.0.0/entityTypes/urn:vcloud:type:cse:nativeCluster:2.0.0

During handling of the above exception, another exception occurred:

**Comment by sreejesh-d** [comment]
Issue is solved after publishing the right bundle.

**Comment by sreejesh-d** [comment]
Issue is solved after publishing the right bundle.
