### ISSUE TITLE
CSE 3.1.1 causes vCD 10.3.1 cell DB connectivity drop

### ISSUE THREAD

**Issue by an0nz** [vmware/container-service-extension#1284]
### Describe the bug

When creating a TKGm cluster using CSE 3.1.1 on vCD 10.3.1 upon completion when CSE logs out of vCD errors are thrown in the CSE debug log (below) and vCD emails the admins `VMware Cloud Director cell with IP address  x.x.x.x is successful in reconnecting to the database .`

The same issue occurs after a failed deployment completes its rollback, the error does not occur when deleting a cluster.

22-01-13 16:33:30 | mqtt_publisher:116 - send_response | Request Id: dd4012df-0b01-499b-b41d-f2b317c1fe4d | DEBUG :: publish return (rc, msg_id): (0, 244)
22-01-13 16:33:31 | cluster_service_2_x_tkgm:2399 - _get_kube_config_from_control_plane_vm | Request Id: dd4012df-0b01-499b-b41d-f2b317c1fe4d | DEBUG :: Got kubeconfig from control plane extra configuration successfully
22-01-13 16:33:32 | cluster_service_2_x_tkgm:945 - _create_cluster_async | Request Id: dd4012df-0b01-499b-b41d-f2b317c1fe4d | DEBUG :: Created cluster 'k8s-tkg-test' (urn:vcloud:entity:cse:nativeCluster:e6e070bd-77e0-486b-85ef-6c4c0d689303)
22-01-13 16:33:32 | cluster_service_2_x_tkgm:1714 - _update_task | Request Id: dd4012df-0b01-499b-b41d-f2b317c1fe4d | DEBUG :: Sending behavior response:{'type': 'BEHAVIOR_RESPONSE', 'headers': {'taskId': 'ef5fc426-e362-4765-af94-8273582cd4b0', 'entityId': 'urn:vcloud:entity:cse:nativeCluster:e6e070bd-77e0-486b-85ef-6c4c0d689303', 'contentType': 'application/vnd.vmware.vcloud.task+json'}, 'payload': '{"status": "success", "result": {"resultContent": "Created cluster \'k8s-tkg-test\' (urn:vcloud:entity:cse:nativeCluster:e6e070bd-77e0-486b-85ef-6c4c0d689303)"}}'}
22-01-13 16:33:32 | mqtt_publisher:116 - send_response | Request Id: dd4012df-0b01-499b-b41d-f2b317c1fe4d | DEBUG :: publish return (rc, msg_id): (0, 245)
22-01-13 16:33:32 | mqtt_consumer:117 - on_disconnect | INFO :: MQTT disconnect with reason: 1
22-01-13 16:33:32 | operation_context:134 - end | Request Id: dd4012df-0b01-499b-b41d-f2b317c1fe4d | DEBUG :: Failed to logout user: svc_cseat api_version: Default api version.
Traceback (most recent call last):
  File "/opt/cse/python/lib/python3.7/site-packages/container_service_extension/security/context/operation_context.py", line 128, in end
    sysadmin_user_context.client.logout()
  File "/opt/cse/python/lib/python3.7/site-packages/pyvcloud/vcd/client.py", line 1140, in logout
    result = self._do_request('DELETE', uri)
  File "/opt/cse/python/lib/python3.7/site-packages/pyvcloud/vcd/client.py", line 1260, in _do_request
    _objectify_response(response, objectify_results))
  File "/opt/cse/python/lib/python3.7/site-packages/pyvcloud/vcd/client.py", line 725, in _objectify_response
    return objectify.fromstring(response.content)
  File "src/lxml/objectify.pyx", line 1998, in lxml.objectify.fromstring
  File "src/lxml/etree.pyx", line 3252, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1912, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1800, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1141, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "<string>", line 11
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: meta line 9 and head, line 11, column 8
22-01-13 16:33:33 | mqtt_consumer:100 - on_connect | INFO :: MQTT client connected with result code 0 and flags {'session present': 1}
22-01-13 16:33:33 | mqtt_consumer:114 - on_subscribe | INFO :: MQTT client subscribed with given_qos: (2,)
22-01-13 16:33:58 | mqtt_consumer:50 - process_behavior_message | Request Id: f6d9e84d-20c6-44a2-ab30-b363d8f020ae | DEBUG :: Received behavior invocation: urn:vcloud:behavior-interface:createCluster:cse:k8s:1.0.0 on entityId:urn:vcloud:entity:cse:nativeCluster:bafa37d7-a0e8-49af-b8db-7faa57635c06 with requestId: f846c470-3f22-49a2-a143-364d9045b88d
22-01-13 16:33:59 | behavior_handler:48 - exception_handler_wrapper | Request Id: f6d9e84d-20c6-44a2-ab30-b363d8f020ae | ERROR :: Start tag expected, '<' not found, line 1, column 1 (<string>, line 1)
Traceback (most recent call last):
  File "/opt/cse/python/lib/python3.7/site-packages/container_service_extension/server/behavior_handler.py", line 43, in exception_handler_wrapper
    result = func(*args, **kwargs)
  File "/opt/cse/python/lib/python3.7/site-packages/container_service_extension/server/behavior_handler.py", line 71, in create_cluster
    sysadmin_client=behavior_ctx.op_ctx.sysadmin_client,
  File "/opt/cse/python/lib/python3.7/site-packages/container_service_extension/security/context/operation_context.py", line 46, in sysadmin_client
    return self.sysadmin_user.client
  File "/opt/cse/python/lib/python3.7/site-packages/container_service_extension/security/context/operation_context.py", line 60, in sysadmin_user
    return self.get_sysadmin_user_context(api_version)
  File "/opt/cse/python/lib/python3.7/site-packages/container_service_extension/security/context/operation_context.py", line 81, in get_sysadmin_user_context
    self._update_sysadmin_user_context_map(api_version=api_version)
  File "/opt/cse/python/lib/python3.7/site-packages/container_service_extension/security/context/operation_context.py", line 106, in _update_sysadmin_user_context_map
    api_version=api_version)
  File "/opt/cse/python/lib/python3.7/site-packages/container_service_extension/common/utils/pyvcloud_utils.py", line 99, in get_sys_admin_client
    client.set_credentials(credentials)
  File "/opt/cse/python/lib/python3.7/site-packages/pyvcloud/vcd/client.py", line 1065, in set_credentials
    token=access_token, is_jwt_token=True)
  File "/opt/cse/python/lib/python3.7/site-packages/pyvcloud/vcd/client.py", line 1116, in rehydrate_from_token
    _objectify_response(response))
  File "/opt/cse/python/lib/python3.7/site-packages/pyvcloud/vcd/client.py", line 725, in _objectify_response
    return objectify.fromstring(response.content)
  File "src/lxml/objectify.pyx", line 1998, in lxml.objectify.fromstring
  File "src/lxml/etree.pyx", line 3252, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1912, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1800, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1141, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1
22-01-13 16:33:59 | behavior_dispatcher:79 - process_behavior_request | Request Id: f6d9e84d-20c6-44a2-ab30-b363d8f020ae | ERROR :: Error while executing handler: {'majorErrorCode': 500, 'minorErrorCode': <MinorErrorCode.DEFAULT_ERROR_CODE: -1>, 'message': "Start tag expected, '<' not found, line 1, column 1 (<string>, line 1)"}
Traceback (most recent call last):
  File "/opt/cse/python/lib/python3.7/site-packages/container_service_extension/server/behavior_handler.py", line 43, in exception_handler_wrapper
    result = func(*args, **kwargs)
  File "/opt/cse/python/lib/python3.7/site-packages/container_service_extension/server/behavior_handler.py", line 71, in create_cluster
    sysadmin_client=behavior_ctx.op_ctx.sysadmin_client,
  File "/opt/cse/python/lib/python3.7/site-packages/container_service_extension/security/context/operation_context.py", line 46, in sysadmin_client
    return self.sysadmin_user.client
  File "/opt/cse/python/lib/python3.7/site-packages/container_service_extension/security/context/operation_context.py", line 60, in sysadmin_user
    return self.get_sysadmin_user_context(api_version)
  File "/opt/cse/python/lib/python3.7/site-packages/container_service_extension/security/context/operation_context.py", line 81, in get_sysadmin_user_context
    self._update_sysadmin_user_context_map(api_version=api_version)
  File "/opt/cse/python/lib/python3.7/site-packages/container_service_extension/security/context/operation_context.py", line 106, in _update_sysadmin_user_context_map
    api_version=api_version)
  File "/opt/cse/python/lib/python3.7/site-packages/container_service_extension/common/utils/pyvcloud_utils.py", line 99, in get_sys_admin_client
    client.set_credentials(credentials)
  File "/opt/cse/python/lib/python3.7/site-packages/pyvcloud/vcd/client.py", line 1065, in set_credentials
    token=access_token, is_jwt_token=True)
  File "/opt/cse/python/lib/python3.7/site-packages/pyvcloud/vcd/client.py", line 1116, in rehydrate_from_token
    _objectify_response(response))
  File "/opt/cse/python/lib/python3.7/site-packages/pyvcloud/vcd/client.py", line 725, in _objectify_response
    return objectify.fromstring(response.content)
  File "src/lxml/objectify.pyx", line 1998, in lxml.objectify.fromstring
  File "src/lxml/etree.pyx", line 3252, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1912, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1800, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1141, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/cse/python/lib/python3.7/site-packages/container_service_extension/server/behavior_dispatcher.py", line 71, in process_behavior_request
    return MAP_BEHAVIOR_ID_TO_HANDLER_METHOD[behavior_id](behavior_ctx)
  File "/opt/cse/python/lib/python3.7/site-packages/container_service_extension/server/behavior_handler.py", line 50, in exception_handler_wrapper
    raise cse_exception.InternalServerRequestError(error_message=str(error))  # noqa: E501
container_service_extension.exception.exceptions.InternalServerRequestError: Start tag expected, '<' not found, line 1, column 1 (<string>, line 1)
22-01-13 16:33:59 | mqtt_publisher:116 - send_response | Request Id: f6d9e84d-20c6-44a2-ab30-b363d8f020ae | DEBUG :: publish return (rc, msg_id): (0, 247)
22-01-13 16:33:59 | mqtt_consumer:60 - process_behavior_message | Request Id: f6d9e84d-20c6-44a2-ab30-b363d8f020ae | DEBUG :: MQTT response: {'type': 'BEHAVIOR_RESPONSE', 'headers': {'taskId': '72bb7f6e-cad3-4e24-9b09-e32588a7219d', 'entityId': 'urn:vcloud:entity:cse:nativeCluster:bafa37d7-a0e8-49af-b8db-7faa57635c06', 'contentType': 'application/vnd.vmware.vcloud.task+json'}, 'payload': '{"status": "error", "error": {"majorErrorCode": 500, "minorErrorCode": -1, "message": "Start tag expected, \'<\' not found, line 1, column 1 (<string>, line 1)"}}'}
22-01-13 16:34:07 | request_dispatcher:857 - process_request | Request Id: 9ce45f52-a213-49a4-8ced-f71e92e7b0bf | DEBUG :: Incoming request message: {"id": "45f83b03-6053-4758-aa85-10c367ef3173", "method": "GET", "requestUri": "/api/pks/ovdcs", "queryString": null, "protocol": "HTTP/1.1", "scheme": "https", "remoteAddr": "198.41.238.119", "remotePort": 40474, "localAddr": "x.x.x.x", "localPort": 443, "headers": {"sec-fetch-mode": "cors", "Cookie": "vcloud_jwt=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; vcloud_session_id=xxxxxxxxxxxxxxxxxxx; _pk_ses.1.4ac8=0; cf_use_ob=0; __cflb=xxxxxxxxxxxxxxxxxxx; _pk_id.1.4ac8=xxxxxxxxxxxxxxxxxxx", "sec-fetch-site": "same-origin", "CF-RAY": "6ccb91297b6ba43f-AKL", "Accept": "application/*+json;version=36.0, application/json;version=36.0", "Connection": "keep-alive", "X-Forwarded-Proto": "https", "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 Edg/96.0.1054.62", "Referer": "https://vcd.mydomain.com/tenant/NOCTest-PMD/plugins/Vk12YXJl/cse", "Host": "vcd.mydomain.com, "CF-Visitor": "{\"scheme\":\"https\"}", "CDN-Loop": "cloudflare", "Accept-Encoding": "gzip", "CF-Connecting-IP": "y.y.y.y", "Authorization": [[REDACTED], "sec-ch-ua": "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"96\", \"Microsoft Edge\";v=\"96\"", "sec-ch-ua-mobile": "?0", "sec-ch-ua-platform": "\"Windows\"", "X-Forwarded-For": "y.y.y.y", "Accept-Language": "en-US,en;q=0.9", "Content-Type": "application/*+json", "sec-fetch-dest": "empty"}, "body": "", "statusCode": 0, "request": true}
22-01-13 16:34:07 | request_dispatcher:857 - process_request | Request Id: ba619322-2227-4582-992d-62d90c54f9f1 | DEBUG :: Incoming request message: {"id": "126713cb-0b21-4659-b190-a9accf81516a", "method": "GET", "requestUri": "/api/pks/clusters", "queryString": null, "protocol": "HTTP/1.1", "scheme": "https", "remoteAddr": "198.41.238.119", "remotePort": 61678, "localAddr": "x.x.x.x", "localPort": 443, "headers": {"sec-fetch-mode": "cors", "Cookie": "vcloud_jwt=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; vcloud_session_id=xxxxxxxxxxxxxxxxxxx; _pk_ses.1.4ac8=0; cf_use_ob=0; __cflb=xxxxxxxxxxxxxxxxxxx; _pk_id.1.4ac8=xxxxxxxxxxxxxxxxxxx", "sec-fetch-site": "same-origin", "CF-RAY": "6ccb91298b6ea43f-AKL", "Accept": "application/*+json;version=36.0, application/json;version=36.0", "Connection": "keep-alive", "X-Forwarded-Proto": "https", "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 Edg/96.0.1054.62", "Referer": "https://vcd.mydomain.com/tenant/NOCTest-PMD/plugins/Vk13YXJl/cse", "Host": "vcd.mydomain.com", "CF-Visitor": "{\"scheme\":\"https\"}", "CDN-Loop": "cloudflare", "Accept-Encoding": "gzip", "CF-Connecting-IP": "y.y.y.y", "Authorization": [[REDACTED], "sec-ch-ua": "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"96\", \"Microsoft Edge\";v=\"96\"", "sec-ch-ua-mobile": "?0", "sec-ch-ua-platform": "\"Windows\"", "X-Forwarded-For": "y.y.y.y", "Accept-Language": "en-US,en;q=0.9", "Content-Type": "application/*+json", "sec-fetch-dest": "empty"}, "body": "", "statusCode": 0, "request": true}
22-01-13 16:34:07 | request_dispatcher:857 - process_request | Request Id: 12242b7d-a64d-4073-98df-3a32f864fd0d | DEBUG :: Incoming request message: {"id": "028d3569-d08e-43e3-903a-51a66692f7be", "method": "GET", "requestUri": "/api/cse/templates/tkgm", "queryString": null, "protocol": "HTTP/1.1", "scheme": "https", "remoteAddr": "198.41.238.119", "remotePort": 40476, "localAddr": "x.x.x.x", "localPort": 443, "headers": {"sec-fetch-mode": "cors", "Cookie": "vcloud_jwt=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; vcloud_session_id=xxxxxxxxxxxxxxxxxxx; _pk_ses.1.4ac8=0; cf_use_ob=0; __cflb=xxxxxxxxxxxxxxxxxxx; _pk_id.1.4ac8=xxxxxxxxxxxxxxxxxxx", "sec-fetch-site": "same-origin", "CF-RAY": "6ccb91298b70a43f-AKL", "Accept": "application/*+json;version=36.0, application/json;version=36.0", "Connection": "keep-alive", "X-Forwarded-Proto": "https", "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 Edg/96.0.1054.62", "Referer": "https://vcd.mydomain.com/tenant/NOCTest-PMD/plugins/Vk13YXJl/cse", "Host": "vcd.mydomain.com", "CF-Visitor": "{\"scheme\":\"https\"}", "CDN-Loop": "cloudflare", "Accept-Encoding": "gzip", "CF-Connecting-IP": "y.y.y.y", "Authorization": [[REDACTED], "sec-ch-ua": "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"96\", \"Microsoft Edge\";v=\"96\"", "sec-ch-ua-mobile": "?0", "sec-ch-ua-platform": "\"Windows\"", "X-Forwarded-For": "y.y.y.y", "Accept-Language": "en-US,en;q=0.9", "Content-Type": "application/*+json", "sec-fetch-dest": "empty"}, "body": "", "statusCode": 0, "request": true}
22-01-13 16:34:07 | exception_handler:53 - exception_handler_wrapper | Request Id: ba619322-2227-4582-992d-62d90c54f9f1 | ERROR :: Traceback (most recent call last):
  File "/opt/cse/python/lib/python3.7/site-packages/container_service_extension/exception/exception_handler.py", line 37, in exception_handler_wrapper
    result = func(*args, **kwargs)
  File "/opt/cse/python/lib/python3.7/site-packages/container_service_extension/server/request_dispatcher.py", line 1004, in process_request
    body_content = handler_method(request_data, operation_ctx)
  File "/opt/cse/python/lib/python3.7/site-packages/container_service_extension/lib/telemetry/telemetry_handler.py", line 113, in wrapper
    raise err
  File "/opt/cse/python/lib/python3.7/site-packages/container_service_extension/lib/telemetry/telemetry_handler.py", line 107, in wrapper
    ret_value = func(*args, **kwargs)
  File "/opt/cse/python/lib/python3.7/site-packages/container_service_extension/server/request_handlers/pks/pks_cluster_handler.py", line 50, in cluster_list
    _raise_error_if_pks_not_enabled()
  File "/opt/cse/python/lib/python3.7/site-packages/container_service_extension/server/request_handlers/pks/pks_cluster_handler.py", line 300, in _raise_error_if_pks_not_enabled
    raise CseServerError('CSE is not configured to work with PKS.')
container_service_extension.exception.exceptions.CseServerError: CSE is not configured to work with PKS.

### Reproduction steps

```bash
CSE 3.1.1
vCD 10.3.1 load balanced behind Cloudflare WAF
NSX-T 3.1.3.1
NSX-ALB (Avi) 21.1.2

1. Fresh Installation of CSE 3.1.1 using Python 3.7.x venv on Ubuntu 20.04 LTS
2. CSE Configured to use MQTT without VCS config and `no_vc_communication_mode: true`, all others as per sample other than broker specifics
3. TKGm OVA's downloaded from VMware and imported with `cse template import -F`
4. CSE Installed using `cse install -t -k ~/.ssh/id_rsa.pub`, -t is required due to no VCS config
5. Additional rights added to rights bundle for TKGm as per https://vmware.github.io/container-service-extension/cse3_1/RBAC.html
6. CSE:NATIVECLUSTER rights added to the tenant admin role
7. oVDC setup with NSX-T edge gateway and a routed network
8. Go to the CSE UI Plugin and deploy a cluster using TKGm
```

### Expected behavior

CSE logs out successfully and vCD does not temporarily lose DB connectivity

**Comment by rocknes** [comment]
CSE has no control over the connectivity between VCD and it's database. If a REST call from CSE is causing this issue, then VCD team should look into it, since CSE uses only standard REST calls of VCD, and a REST call affecting DB connection is a matter of serious concern.

If this is a multi site VCD installation, there is a bug in VCD where the cell crashes while reading messages from MQTT bus. A hot patch for it has been issued, try upgrading the VCD build. 
Btw when cell goes down, connectivity between VCD cell and DB will be impacted too, that might explain the observed behavior.

The errors seen in the CSE log can be explained by the above too. If the cell goes down then subsequent REST calls return a `service unavailable`  message but it is sent as plain/text instead of application/xml which pyvcloud can't handle.

Regards
Aritra Sen

**Comment by an0nz** [comment]
Thanks for the quick response, looks like vCD 10.3.2 released yesterday/today and has the MQTT fix you mentioned along with some other features we have been waiting for. I shall run an upgrade and retest.

**Comment by an0nz** [comment]
After updating to vCD 10.3.2 this issue no longer occurs.

This is not a multi-site vCD installation just a standard primary + 2 standby node configuration.
Whatever CSE was doing with MQTT and vCD must have been triggering the bug as it occurred at the exact same stage during every cluster deployment.

**Comment by goelaashima** [comment]
Hello @an0nz - Thanks for following this through and reporting back the resolution. Glad it worked out.

Aashima
