### ISSUE TITLE
Photon template customization fails

### ISSUE THREAD

**Issue by mgaruccio** [vmware/container-service-extension#144]
The Photon OS configuration step fails with an error about invalid credentials.  Tried a few different passwords to ensure there wasn't some sort of special character issue but it failed with three different passwords.  The ubuntu template completes with no issues.

CSE Version: 1.2.2
VCD Version: 9.5.0.10264774

Full error text:
```
Traceback (most recent call last):
  File "/home/expedient/cse/lib64/python3.6/site-packages/container_service_extension/config.py", line 569, in create_template
    callback=wait_for_guest_execution_callback)
  File "/home/expedient/cse/lib64/python3.6/site-packages/vsphere_guest_run/vsphere.py", line 203, in execute_script_in_guest
    self.upload_file_to_guest(vm, user, password, content, target)
  File "/home/expedient/cse/lib64/python3.6/site-packages/vsphere_guest_run/vsphere.py", line 143, in upload_file_to_guest
    False)
  File "/home/expedient/cse/lib64/python3.6/site-packages/pyVmomi/VmomiSupport.py", line 580, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/home/expedient/cse/lib64/python3.6/site-packages/pyVmomi/VmomiSupport.py", line 386, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/home/expedient/cse/lib64/python3.6/site-packages/pyVmomi/SoapAdapter.py", line 1374, in InvokeMethod
    raise obj # pylint: disable-msg=E0702
pyVmomi.VmomiSupport.vim.fault.InvalidGuestLogin: (vim.fault.InvalidGuestLogin) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'Failed to authenticate with the guest operating system using the supplied credentials.',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) []
```

**Comment by fjmatos** [comment]
Same here with  VCloud Director 9.5 GA + CSE 1.2.2 + vcd-cli 21.0.0

**Comment by harshneelmore** [comment]
Following is a workaround for the above issue- 
https://github.com/vmware/container-service-extension/issues/145#issuecomment-434964458

And PR https://github.com/vmware/container-service-extension/pull/146 has been created to fix the data file installation

**Comment by fjmatos** [comment]
This workaround worked for me. 
Now photon and Ubuntu cluster deploy well.

**Comment by mgaruccio** [comment]
workaround functioned for me as well.  Thank you.
