### ISSUE TITLE
Ubuntu 16.04 customization fails after manually performing issue 101 

### ISSUE THREAD

**Issue by nbarve** [vmware/container-service-extension#157]
cse 1.2.2 and vcd 9.1 

Photon customisation works fine, but when it comes to ubuntu 16.04 and running cse install i get an error. see below. 

The following package was automatically installed and is no longer required:
  containerd.io
Use 'apt autoremove' to remove it.
The following packages will be REMOVED:
  docker-ce-cli
The following packages will be DOWNGRADED:
  docker-ce
0 upgraded, 0 newly installed, 1 downgraded, 1 to remove and 3 not upgraded.

Customization attempt #5 failed
Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/container_service_extension/config.py", line 371, in install_cse
    catalog, no_capture, template, ssh_key)
  File "/root/.local/lib/python3.6/site-packages/container_service_extension/config.py", line 593, in create_template
    raise Exception('Failed to customize VM')
Exception: Failed to customize VM

Can't create or update template 'ubuntu-16.04' 'cse': ubuntu-16.04-server-cloudimg-amd64-k8s
Traceback (most recent call last):
  File "/usr/bin/cse", line 11, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/.local/lib/python3.6/site-packages/container_service_extension/cse.py", line 206, in install
    amqp_install, ext_install)
  File "/root/.local/lib/python3.6/site-packages/container_service_extension/config.py", line 392, in install_cse
    if should_configure_amqp(client, config['amqp'], amqp_install):
  File "/root/.local/lib/python3.6/site-packages/container_service_extension/config.py", line 646, in should_configure_amqp
    current_settings = to_dict(amqp_service.get_settings())
  File "/root/.local/lib/python3.6/site-packages/pyvcloud/vcd/amqp.py", line 43, in get_settings
    return self.client.get_resource(self.href)
  File "/root/.local/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 1099, in get_resource
    'GET', uri, objectify_results=objectify_results)
  File "/root/.local/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 861, in _do_request
    response), _objectify_response(response, objectify_results))
  File "/root/.local/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 869, in _response_code_to_exception
    raise UnauthorizedException(sc, request_id, objectify_response)
pyvcloud.vcd.exceptions.UnauthorizedException: Status code: 401, <empty response body> (request id: 1e91b92f-dc65-458c-9308-2b3f12a85cb6)

I had to login to guest and run the dkpg and install open-vm-tools to continue (issue 101), but after that i recieved the above issue. any hints ?

https://github.com/vmware/container-service-extension/issues/101

**Comment by andrew-ni** [comment]
The traceback points to the AMQP configuration step as a failure point, and this would be caused by CSE installation not being able to connect to the AMQP server for some reason.

This traceback seems independent to the real issue though, which is template customization failure. I'm not seeing anything related to template customization failure in the traceback, but because you said Photon customization worked, then I would think the issue would be vcd-related (something like not enough IPs, or not enough storage, or a connection couldn't be made). Do you have logs for this issue? And what are you seeing in console output?
