### ISSUE TITLE
Unable to get cluster configuration `File /root/.kube/config was not found`

### ISSUE THREAD

**Issue by frenchtoasters** [vmware/container-service-extension#160]
After creating my cluster I attempted to run:

```
vcd cse cluster config mycluster > ~/.kube/config
```

And got the following error message:

```
root@photon-machine [ ~/.kube ]# vcd cse cluster config TylerWasHereUbuntu > ~/.kube/config
InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised.
Usage: vcd cse cluster config [OPTIONS] NAME
Try "vcd cse cluster config -h" for help.

Error: (vim.fault.FileNotFound) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'File /root/.kube/config was not found',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   file = '/root/.kube/config'
}
```

The file is actually there:

```
root@photon-machine [ ~ ]# pwd
/root
root@photon-machine [ ~ ]# ls -al ~/.kube/
total 8
drwxr-x--- 2 root root 4096 Nov 19 15:18 .
drwxr-x--- 7 root root 4096 Nov 19 15:18 ..
-rw-r----- 1 root root    0 Nov 19 15:18 config
```

The cluster shows up:

```
root@photon-machine [ ~ ]# vcd cse cluster list
InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised.
IP master      VMs  name                status      template      vdc
-----------  -----  ------------------  ----------  ------------  -----------
192.168.0.4      4  TylerWasHereUbuntu  POWERED_ON  ubuntu-16.04  CSE Tenant2
```

I also noticed that the command found (here)[https://vmware.github.io/container-service-extension/#example] to get the cluster configuration doesnt actually read the file that I pass to the command and just uses the default of `/root/.kube/config`. I looked at the help for `cluster config` command and tried to use the `-s` option for that command and got the same error. 

Looking at the `vcd.log` for the last message from the cluster creation I got this:

```
2018-11-16 22:35:35,747 | DEBUG | pyvcloud.vcd.cl | client          | _log_request | Request uri (GET): https://labvcd.example.net/api/task/21b30e88-173b-4608-a8a1-4cd3aa16f95f
2018-11-16 22:35:35,747 | DEBUG | pyvcloud.vcd.cl | client          | _log_request | Request headers: {'User-Agent': 'python-requests/2.20.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/*+xml;version=30.0', 'Connection': 'keep-alive', 'x-vcloud-authorization': 'dfaaa160a71d4cdcb4bdfeb2cdfa1a47', 'Cookie': 'sis-vcds-session=srv-GG21aSbQ5QpeseDeAQsnUA|W+9GN'}
2018-11-16 22:35:35,747 | DEBUG | pyvcloud.vcd.cl | client          | _log_request | Response status code: 200
2018-11-16 22:35:35,747 | DEBUG | pyvcloud.vcd.cl | client          | _log_request | Response headers: {'Date': 'Fri, 16 Nov 2018 22:35:35 GMT', 'X-VMWARE-VCLOUD-REQUEST-ID': '93cf18b7-005d-42bc-b759-26bc4aa957c0', 'X-VMWARE-VCLOUD-ACCESS-TOKEN': 'eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ0ZnJlbmNoIiwiaXNzIjoiNzA5ZTIyNjQtYzE4Mi00NTQ2LThkMjYtY2Y1NDZmZDcyMjE3QGU0NDU4YTg5LTc3NDItNDRjZC05ZTY1LTE0ODFkYWJlNjM1NiIsImV4cCI6MTU0MjQ5MjMzNCwidmVyc2lvbiI6InZjbG91ZF8xLjAiLCJqdGkiOiJkZmFhYTE2MGE3MWQ0Y2RjYjRiZGZlYjJjZGZhMWE0NyJ9.Z9upHms7PKrMgShsD_ql0a4EoNjB9OwkZfDUDGxhbiBITzWR3mxA1KvJtVrdK-nP3UcZbeH98ZdXdn04SUrZUsIWosiXiR1-kFyz4SHwg4p61wW8M2FDv9PZWx5B6IOaA8zYjYhJuPIqz8uvsHnVjjkTMwfSicqtpUX0BBROff2QQe5ivoWQiiLqT4--8hpL-L5ze8WwSDgKHI7WqWtbcZE6ggfm7SQcRDHH6wqBQ9fhKYB8_UUNy-eUD4H5-mq9aCOhp5UfgPW-NaIr3evVSEX6lwMAVbPzth7cIkAsxpyd1Gui6ohFQuIn938h6-YAl5s5musBFJQt4WdUhCUX7A', 'X-VMWARE-VCLOUD-TOKEN-TYPE': 'Bearer', 'x-vcloud-authorization': 'dfaaa160a71d4cdcb4bdfeb2cdfa1a47', 'Content-Type': 'application/vnd.vmware.vcloud.task+xml;version=30.0', 'X-VMWARE-VCLOUD-REQUEST-EXECUTION-TIME': '72', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding, User-Agent', 'Connection': 'close', 'Set-Cookie': 'sis-vcds-session=srv-GG21aSbQ5QpeseDeAQsnUA|W+9GO; path=/', 'Cache-control': 'private'}
2018-11-16 22:35:35,748 | DEBUG | pyvcloud.vcd.cl | client          | _log_request | Response body: <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Task xmlns="http://www.vmware.com/vcloud/v1.5" xmlns:ovf="http://schemas.dmtf.org/ovf/envelope/1" xmlns:vssd="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData" xmlns:common="http://schemas.dmtf.org/wbem/wscim/1/common" xmlns:rasd="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData" xmlns:vmw="http://www.vmware.com/schema/ovf" xmlns:ovfenv="http://schemas.dmtf.org/ovf/environment/1" xmlns:vmext="http://www.vmware.com/vcloud/extension/v1.5" xmlns:ns9="http://www.vmware.com/vcloud/versions" cancelRequested="false" endTime="2018-11-16T17:35:33.160-05:00" expiryTime="2019-02-14T17:07:13.997-05:00" operation="create cluster" operationName="create_cluster" serviceNamespace="vcloud.cse" startTime="2018-11-16T17:07:13.997-05:00" status="error" name="task" id="urn:vcloud:task:21b30e88-173b-4608-a8a1-4cd3aa16f95f" href="https://labvcd.example.net/api/task/21b30e88-173b-4608-a8a1-4cd3aa16f95f" type="application/vnd.vmware.vcloud.task+xml">
    <Owner href="urn:cse:cluster:ee4023b5-e36b-44b6-bb2a-4673ef40e55a" name="TylerWasHereUbuntu" type="application/vcloud.cse.cluster+xml"/>
    <Error majorErrorCode="500" message="list index out of range" minorErrorCode="INTERNAL_SERVER_ERROR"/>
    <User href="https://labvcd.example.net/api/admin/user/6b146b67-f68d-4dc6-bc03-05647525056f" name="tfrench" type="application/vnd.vmware.admin.user+xml"/>
    <Organization href="https://labvcd.example.net/api/org/709e2264-c182-4546-8d26-cf546fd72217" name="Marrone-Land" type="application/vnd.vmware.vcloud.org+xml"/>
    <Details>list index out of range</Details>
</Task>
```

And here is the same error im getting from the command but from the `vcd.log`:

```
2018-11-19 15:07:21,837 | DEBUG | pyvcloud.vcd.cl | client          | _log_request | Request uri (GET): https://labvcd.example.net/api/cse/TylerWasHereUbuntu/config
2018-11-19 15:07:21,837 | DEBUG | pyvcloud.vcd.cl | client          | _log_request | Request headers: {'User-Agent': 'python-requests/2.20.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'text/x-yaml;version=30.0', 'Connection': 'keep-alive', 'x-vcloud-authorization': '95331488cab24b9f95d6ff71fbf3d785'}
2018-11-19 15:07:21,837 | DEBUG | pyvcloud.vcd.cl | client          | _log_request | Response status code: 500
2018-11-19 15:07:21,838 | DEBUG | pyvcloud.vcd.cl | client          | _log_request | Response headers: {'Date': 'Mon, 19 Nov 2018 15:07:19 GMT', 'X-VMWARE-VCLOUD-REQUEST-ID': 'e21317ec-d21c-4d73-8697-7f535dd3c63a', 'X-VMWARE-VCLOUD-ACCESS-TOKEN': 'eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ0ZnJlbmNoIiwiaXNzIjoiNzA5ZTIyNjQtYzE4Mi00NTQ2LThkMjYtY2Y1NDZmZDcyMjE3QGU0NDU4YTg5LTc3NDItNDRjZC05ZTY1LTE0ODFkYWJlNjM1NiIsImV4cCI6MTU0MjcyNDA3MywidmVyc2lvbiI6InZjbG91ZF8xLjAiLCJqdGkiOiI5NTMzMTQ4OGNhYjI0YjlmOTVkNmZmNzFmYmYzZDc4NSJ9.DP_OCiz2T2-zRK_K3efvSa00_1xtBcFW-J8Z52hTxwCSiKyOKxgwIJckfEjJlT0kzOIytZHKR1sqiuvl5gp1fEeLlYCnXN9bsI2S1MkKh7t8ZMkrGv20AaP1Uj_mrGAK0AncF0hQxbxSOD7VcLZmYkXMNftcTbc4rQFF6p7XyrtlQKXBr29xjNmjAKVhqdUN92K_uH8W5DaJCdQotJoGzBpX9kAVc2oJFaCl5fqebOoXfpcjlsy1-h0gM3dUQJWah0HM9e9T72Q6fyYu2Wl8_JNv2yZS2AU_Bbdw9Ng6QbHPGwWht3Q5guhlbRKYwItbEOLdk32xT0p0n6_VxpVVFg', 'X-VMWARE-VCLOUD-TOKEN-TYPE': 'Bearer', 'x-vcloud-authorization': '95331488cab24b9f95d6ff71fbf3d785', 'Content-Type': 'text/x-yaml;version=30.0', 'Content-Length': '280', 'Set-Cookie': 'sis-vcds-session=srv-S1QSS/FnMnB2GjMDO7Z15A|W/LRn; path=/'}
2018-11-19 15:07:21,838 | DEBUG | pyvcloud.vcd.cl | client          | _log_request | Response body: {"message": "(vim.fault.FileNotFound) {\n   dynamicType = <unset>,\n   dynamicProperty = (vmodl.DynamicProperty) [],\n   msg = 'File /root/.kube/config was not found',\n   faultCause = <unset>,\n   faultMessage = (vmodl.LocalizableMessage) [],\n   file = '/root/.kube/config'\n}"}
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/container_service_extension/client/cse.py", line 273, in config
    cluster_config = cluster.get_config(name)
  File "/usr/lib/python3.6/site-packages/container_service_extension/client/cluster.py", line 160, in get_config
    return self._process_response(response)
  File "/usr/lib/python3.6/site-packages/container_service_extension/client/cluster.py", line 37, in _process_response
    raise Exception(content['message'])
Exception: (vim.fault.FileNotFound) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'File /root/.kube/config was not found',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   file = '/root/.kube/config'
}
```

**Comment by frenchtoasters** [comment]
@andrew-ni When running those commands im still getting the same result:

```
root@photon-machine [ ~ ]# cse version
CSE, Container Service Extension for VMware vCloud Director, version 1.2.2
root@photon-machine [ ~ ]# vcd version
vcd-cli, VMware vCloud Director Command Line Interface, 21.0.0
root@photon-machine [ ~ ]# vcd cse cluster config TylerWasHereUbuntu > ~/.kube/config 
InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised.
Usage: vcd cse cluster config [OPTIONS] NAME
Try "vcd cse cluster config -h" for help.

Error: (vim.fault.FileNotFound) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'File /root/.kube/config was not found',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   file = '/root/.kube/config'
}
root@photon-machine [ ~ ]# cat ~/.kube/config 
root@photon-machine [ ~ ]# 
```

Also I tried just running the `vcd cse cluster config TylerWasHereUbuntu` thinking it would just print it back to the console and actually got the same error message:

```
root@photon-machine [ ~ ]# vcd cse cluster config TylerWasHereUbuntu 
InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised.
Usage: vcd cse cluster config [OPTIONS] NAME
Try "vcd cse cluster config -h" for help.

Error: (vim.fault.FileNotFound) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'File /root/.kube/config was not found',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   file = '/root/.kube/config'
}
```

Running the command as the root user shouldnt cause permissions issues but are there any specific permissions on the `~/.kube` folder?

**Comment by andrew-ni** [comment]
I'm confused why your command `vcd cse cluster config TylerWasHereUbuntu` tries to look for `.kube/config` file.

I removed my `.kube/config` file from my local setup, and ran the command `vcd cse cluster config mycluster`, and everything worked as expected.

`vcd cse cluster config mycluster` command does not even look for or know about `.kube/config` file, so i'm really stumped here.

From your original logs, it seems as if cluster creation failed/corrupted. CSE does not know that the cluster is corrupt, so `vcd cse cluster list` still shows it. 

I would recommend creating a new cluster. Watch the logs/console output for any signs of failure, and if it fails, then that likely means that your templates are not valid. If this is the case, a reinstall of CSE is needed (delete everything cse-related from vCD, and run `cse install` again). Monitor this new install, and if there's any signs of failure, then this is likely the problem we need to solve. (Example, Data file not found error has been seen in 1.2.2, where CSE script files are misplaced, causing CSE templates to be invalid, workaround is here https://github.com/vmware/container-service-extension/issues/145#issuecomment-434964458)

Once you do that and you're sure that your templates have been installed correctly/cluster has been created without failures, try the config command again.

**Comment by frenchtoasters** [comment]
@andrew-ni After trying to deploy another cluster again it ended with the same `list index out of range error`. Looking at the `cse.log` though I saw this:

```
11-20 15:16:17 urllib3.connectionpool 393 DEBUG    https://172.21.32.12:443 "GET /guestFile?id=4185&token=528ac44b-1135-1303-1784-6f169b78c8884185 HTTP/1.1" 200 81
11-20 15:16:17 cse.cluster  214 DEBUG    process [0, <Response [200]>, <Response [200]>] on vm 'vim.VirtualMachine:vm-10176' finished, exit code: 0
11-20 15:16:17 cse.cluster  373 DEBUG    0
11-20 15:16:17 cse.cluster  374 DEBUG    /tmp/32d268ca-ecd7-11e8-8b3e-005056becb8a.sh: line 2: kubeadm: command not found

11-20 15:16:17 cse.cluster  375 DEBUG    192.168.0.8

11-20 15:16:17 cse.utils    57 ERROR    Data file not found!
11-20 15:16:17 cse.broker   490 ERROR    Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/container_service_extension/broker.py", line 475, in create_cluster_thread
    join_cluster(self.config, vapp, template)
  File "/usr/lib/python3.6/site-packages/container_service_extension/cluster.py", line 274, in join_cluster
    script = tmp_script.format(token=init_info[0], ip=init_info[1])
IndexError: list index out of range

11-20 15:16:17 urllib3.connectionpool 240 DEBUG    Resetting dropped connection: labvcd.example.net
11-20 15:16:17 urllib3.connectionpool 393 DEBUG    https://labvcd.example.net:443 "PUT /api/task/36414522-ee92-4092-adbc-5899685f8fc6 HTTP/1.1" 200 None
```

Looking at that it looks like when the `get_init_info` function was called it didnt find `kubeadm` installed on the template. Is there a list of requirements of things that need to be installed on the templates prior to their use with CSE?
