### ISSUE TITLE
CSE install fails with temp vApp deletion in 1.2.5

### ISSUE THREAD

**Issue by jondwaite** [vmware/container-service-extension#170]
Performing template upgrade with v1.2.5, cse install fails when attempting to remove the temporary vApp after customization has completed (successfully) and the vApp capture to catalog completed (again successfully):

```
...
Customized vApp 'photon2-temp'
Creating template 'photon-custom-hw11-2.0-304b817-k8s' from vApp 'photon2-temp'
vappShutdownGuest: Shutting down Virtual Application photon2-temp(846b9340-6726-4278-9c8d-c36bd8ae08ed)
vappShutdownGuest: Shutting down Virtual Application photon2-temp(846b9340-6726-4278-9c8d-c36bd8ae08ed)
task: 9c1078e5-42a7-40e3-bc75-d5fe6c863bcd, Shut down Virtual Application photon2-temp(846b9340-6726-4278-9c8d-c36bd8ae08ed), result: success
vdcCaptureTemplate: Capturing Virtual Application Template photon-custom-hw11-2.0-304b817-k8s(55c854e8-0538-461f-bf7c-c48edbb8deda)
vdcCaptureTemplate: Capturing Virtual Application Template photon-custom-hw11-2.0-304b817-k8s(55c854e8-0538-461f-bf7c-c48edbb8deda)
task: f788ffa0-66dc-4e76-afde-ce56dac8a01b, Captured Virtual Application Template photon-custom-hw11-2.0-304b817-k8s(55c854e8-0538-461f-bf7c-c48edbb8deda), result: success
Created template 'photon-custom-hw11-2.0-304b817-k8s' from vApp 'photon2-temp'
Deleting vApp 'photon2-temp'
Traceback (most recent call last):
  File "/home/cse/cse/bin/cse", line 11, in <module>
    sys.exit(cli())
  File "/home/cse/cse/lib64/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/cse/cse/lib64/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/cse/cse/lib64/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/cse/cse/lib64/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/cse/cse/lib64/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/cse/cse/lib64/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/cse/cse/lib64/python3.6/site-packages/container_service_extension/cse.py", line 227, in install
    amqp_install=amqp_install, ext_install=ext_install)
  File "/home/cse/cse/lib64/python3.6/site-packages/container_service_extension/config.py", line 516, in install_cse
    org=org)
  File "/home/cse/cse/lib64/python3.6/site-packages/container_service_extension/config.py", line 620, in create_template
    task = vdc.delete_vapp(vapp_name, force=True)
  File "/home/cse/cse/lib64/python3.6/site-packages/pyvcloud/vcd/vdc.py", line 145, in delete_vapp
    href = self.get_resource_href(name)
  File "/home/cse/cse/lib64/python3.6/site-packages/pyvcloud/vcd/vdc.py", line 100, in get_resource_href
    raise EntityNotFoundException('vApp named \'%s\' not found' % name)
pyvcloud.vcd.exceptions.EntityNotFoundException: vApp named 'photon2-temp' not found
```

Exact same issue with the ubuntu-16.04 template (ubuntu1604-temp not found). Since capture of the vApp has completed at the stage where this happens you can complete the install using the --template option to pick the 'other' one.

**Comment by jondwaite** [comment]
One other thing I forgot to mention - when attempting to manually delete the remaining vApp templates, this isn't possible until the vApp is powered-off (even though the status on the vApp already says powered-off), possible that there is a vApp refresh/synchronisation issue preventing the deletion from succeeding.

**Comment by andrew-ni** [comment]
We've had the same experience from another user as well as our own testing done over the past week. This is a known issue from 1.2.4, caused by missing a simple VDC synchronization.

For now, the workaround is to either use 'cleanup: False' in the config file, or manually power-off and delete the vApp (The vApp cannot be powered off because in order to capture it to a template, it must be in 'shutdown' status, which is different than 'powered off'.

This is relatively minor in that it occurs after CSE installation has already succeeded. The template is customized and captured, and it can still be used without issue for cluster deployments.

**Comment by daydrim** [comment]
We have the same experience with the temp vApp deleteion.
We tried to rename vApp 'photon2temp' without dashes - it didn't work
However `vcd vapp detele photon2-temp -f` works ok
