### ISSUE TITLE
vApp shutdown fails when trying to capture template

### ISSUE THREAD

**Issue by hodgesrm** [vmware/container-service-extension#182]
The 'cse install' command sometimes fails when trying to shut down a template vApp prior to capturing it in the logs. The vApp in question was fully running a the time of the failure. 

The command I was running was the following: 
```
cse install -c my-test-config.yaml --ssh-key=$HOME/.ssh/id_rsa.pub --ext config --amqp config
```
It failed with the following message.  The vApp in q
```
Customized vApp 'photon2-temp'
Creating template 'photon-custom-hw11-2.0-304b817-k8s' from vApp 'photon2-temp'
vappShutdownGuest: Shutting down Virtual Application photon2-temp(240d4cce-cd1evappShutdownGuest: Shutting down Virtual Application photon2-temp(240d4cce-cd1e-4c05-a489-3384886964fe)
vappShutdownGuest: Shutting down Virtual Application photon2-temp(240d4cce-cd1evappShutdownGuest: Shutting down Virtual Application photon2-temp(240d4cce-cd1e-4c05-a489-3384886964fe)
vappShutdownGuest: Shut down Virtual Application photon2-temp(240d4cce-cd1e-4c0task: 56a388a9-eaca-4b0a-869f-ff442c925bd2, Shut down Virtual Application photon2-temp(240d4cce-cd1e-4c05-a489-3384886964fe), result: success
Traceback (most recent call last):
  File "/Users/rhodges/workspaces/vcd-cli/environment/cse-doc-test/bin/cse", line 10, in <module>
    sys.exit(cli())
  File "/Users/rhodges/workspaces/vcd-cli/environment/cse-doc-test/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/rhodges/workspaces/vcd-cli/environment/cse-doc-test/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/rhodges/workspaces/vcd-cli/environment/cse-doc-test/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/rhodges/workspaces/vcd-cli/environment/cse-doc-test/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/rhodges/workspaces/vcd-cli/environment/cse-doc-test/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/rhodges/workspaces/vcd-cli/environment/cse-doc-test/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/rhodges/workspaces/vcd-cli/environment/cse-doc-test/lib/python3.6/site-packages/container_service_extension/cse.py", line 227, in install
    amqp_install=amqp_install, ext_install=ext_install)
  File "/Users/rhodges/workspaces/vcd-cli/environment/cse-doc-test/lib/python3.6/site-packages/container_service_extension/config.py", line 516, in install_cse
    org=org)
  File "/Users/rhodges/workspaces/vcd-cli/environment/cse-doc-test/lib/python3.6/site-packages/container_service_extension/config.py", line 613, in create_template
    power_on=not template_config['cleanup'])
  File "/Users/rhodges/workspaces/vcd-cli/environment/cse-doc-test/lib/python3.6/site-packages/container_service_extension/config.py", line 809, in capture_vapp_to_template
    customize_on_instantiate=True, overwrite=True)
  File "/Users/rhodges/workspaces/vcd-cli/environment/cse-doc-test/lib/python3.6/site-packages/pyvcloud/vcd/org.py", line 872, in capture_vapp
    contents=contents)
  File "/Users/rhodges/workspaces/vcd-cli/environment/cse-doc-test/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 1088, in post_linked_resource
    media_type)
  File "/Users/rhodges/workspaces/vcd-cli/environment/cse-doc-test/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 1072, in post_resource
    objectify_results=objectify_results)
  File "/Users/rhodges/workspaces/vcd-cli/environment/cse-doc-test/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 861, in _do_request
    response), _objectify_response(response, objectify_results))
  File "/Users/rhodges/workspaces/vcd-cli/environment/cse-doc-test/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 866, in _response_code_to_exception
    raise BadRequestException(sc, request_id, objectify_response)
pyvcloud.vcd.exceptions.BadRequestException: Status code: 400/BAD_REQUEST, [ 1b7daec4-725d-40be-a32d-b719ecec8f33 ] A VM in the vApp is suspended or powered on. It must be powered off first. (request id: 1b7daec4-725d-40be-a32d-b719ecec8f33)
```
The config.yaml is appended.

**Comment by hodgesrm** [comment]
[test-config.yaml.txt](https://github.com/vmware/container-service-extension/files/2696382/test-config.yaml.txt)

**Comment by hodgesrm** [comment]
CSE is installed from master in a virtualenv using 'python3 setup.py develop'.  Code is fully up to date. Here's the pip freeze output:
```
cachetools==3.0.0
certifi==2018.11.29
chardet==3.0.4
Click==7.0
colorama==0.4.1
-e git+git@github.com:vmware/container-service-extension.git@a71c2a268d3868f207a004f38b7300e28cf8c1f2#egg=container_service_extension
entrypoints==0.2.3
flufl.enum==4.1.1
humanfriendly==4.17
idna==2.8
keyring==12.0.0
lxml==4.2.5
pika==0.12.0
pycryptodome==3.4.11
Pygments==2.3.1
pyvcloud==20.0.1
pyvmomi==6.7.1
PyYAML==3.13
requests==2.21.0
six==1.12.0
tabulate==0.8.2
urllib3==1.24.1
vcd-cli==21.0.0
vsphere-guest-run==0.0.7
```
