### ISSUE TITLE
vCloud  9 - cse 1.2.5 

### ISSUE THREAD

**Issue by EvgBoor** [vmware/container-service-extension#185]
Problem with wrong href when installing CSE. vCloud 9.0.3 + CSE 1.2.5
Logs:
cse install  --config config.yaml.1.2.5
Validating config file 'config.yaml.1.2.5'
Connected to AMQP server (ampq:5672)
InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised.
Connected to vCloud Director (VCD:443)
Connected to vCenter Server 'XXXXX' as 'cse@vsphere.local' (XXXX.local:443)
Config file 'config.yaml.1.2.5' is valid
Installing CSE on vCloud Director using config file 'config.yaml.1.2.5'
Connected to vCD as system administrator: VCD:443
Checking for AMQP exchange 'vcdExchange'
AMQP exchange 'vcdExchange' is ready
vCD and config file AMQP settings are the same. Skipping AMQP configuration
Found 'cse' extension on vCD, enabled=true
Found catalog 'TST'
Traceback (most recent call last):
  File "/home/cse/.local/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 1087, in post_linked_resource
    find_link(resource, rel, media_type).href, contents,
  File "/home/cse/.local/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 1335, in find_link
    raise MissingLinkException(resource.get('href'), rel, media_type)
pyvcloud.vcd.exceptions.MissingLinkException: ('https://vcd.fqdn/api/catalog/b0d9e951-d225-4f62-be5d-d191f5d225f6', <EnumValue: RelationType.PUBLISH [value=publish]>, 'application/vnd.vmware.admin.publishCatalogParams+xml'); href: https://vcd.fqdn/api/catalog/b0d9e951-d225-4f62-be5d-d191f5d225f6, rel: RelationType.PUBLISH, mediaType: application/vnd.vmware.admin.publishCatalogParams+xml

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cse/.local/bin/cse", line 11, in <module>
    sys.exit(cli())
  File "/home/cse/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/cse/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/cse/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/cse/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/cse/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/cse/.local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/cse/.local/lib/python3.6/site-packages/container_service_extension/cse.py", line 227, in install
    amqp_install=amqp_install, ext_install=ext_install)
  File "/home/cse/.local/lib/python3.6/site-packages/container_service_extension/config.py", line 509, in install_cse
    catalog_desc='CSE templates')
  File "/home/cse/.local/lib/python3.6/site-packages/container_service_extension/utils.py", line 403, in create_and_share_catalog
    org.share_catalog(catalog_name)
  File "/home/cse/.local/lib/python3.6/site-packages/pyvcloud/vcd/org.py", line 227, in share_catalog
    contents=params)
  File "/home/cse/.local/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 1091, in post_linked_resource
    "Operation is not supported").with_traceback(e.__traceback__)
  File "/home/cse/.local/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 1087, in post_linked_resource
    find_link(resource, rel, media_type).href, contents,
  File "/home/cse/.local/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 1335, in find_link
    raise MissingLinkException(resource.get('href'), rel, media_type)
pyvcloud.vcd.exceptions.OperationNotSupportedException: Operation is not supported

**Comment by rocknes** [comment]
Seems like the link for publishing catalogs (admin view of catalogs) is missing in vCD's response to GET \api\ctalog\{id} . Will it be possible to upload the cse logs? Pleaes look for the file vcd.log.

**Comment by EvgBoor** [comment]
vcd.log is empty - https://i.imgur.com/3XQH8me.png
--------------------------------------------------------
config:
amqp:
  exchange: vcdExchange
  host: ampq01
  password: FFFFFF
  port: 5672
  prefix: vcd
  routing_key: cse
  ssl: false
  ssl_accept_all: false
  username: admin
  vhost: /

vcd:
  api_version: '28.0'
  host: 10.0.0.0
  log: true
  password: 'FFFFFF'
  port: 443
  username: cse_admin
  verify: false

vcs:
- name: 'VMware'
  password: 'FFFFFF'
  username: cse@vsphere.local
  verify: false

  
service:
  listeners: 5

broker:
  catalog: cse2
  cse_msg_dir: /tmp/cse
  default_template: photon-v2
  ip_allocation_mode: pool
  network: inet
  org: cse
  storage_profile: 'FAST'
  templates:
  - admin_password: guest_os_admin_password
    catalog_item: photon-custom-hw11-2.0-304b817-k8s
    cleanup: true
    cpu: 2
    description: 'PhotonOS v2

      Docker 17.06.0-4

      Kubernetes 1.9.1

      weave 2.3.0'
    mem: 2048
    name: photon-v2
    sha256_ova: cb51e4b6d899c3588f961e73282709a0d054bb421787e140a1d80c24d4fd89e1
    source_ova: http://dl.bintray.com/vmware/photon/2.0/GA/ova/photon-custom-hw11-2.0-304b817.ova
    source_ova_name: photon-custom-hw11-2.0-304b817.ova
    temp_vapp: photon2-temp
  - admin_password: guest_os_admin_password
    catalog_item: ubuntu-16.04-server-cloudimg-amd64-k8s
    cleanup: true
    cpu: 2
    description: 'Ubuntu 16.04

      Docker 18.03.0~ce

      Kubernetes 1.10.1

      weave 2.3.0'
    mem: 2048
    name: ubuntu-16.04
    sha256_ova: 3c1bec8e2770af5b9b0462e20b7b24633666feedff43c099a6fb1330fcc869a9
    source_ova: https://cloud-images.ubuntu.com/releases/xenial/release-20180418/ubuntu-16.04-server-cloudimg-amd64.ova
    source_ova_name: ubuntu-16.04-server-cloudimg-amd64.ova
    temp_vapp: ubuntu1604-temp
  type: default
  vdc: cse_vdc

**Comment by EvgBoor** [comment]
log attached

**Comment by rocknes** [comment]
I guess you have vcd-cli installed too. Can you please run the following commands via vcd-cli?

vcd login 'vcd fqdn/ip' system 'sys admin username' -iw
(enter password when prompted)
vcd org use cse
vcd catalog info cse2

This should generate a vcd.log file in the directory from where the vcd-cli commands were issued. Can you please upload that log file.

**Comment by EvgBoor** [comment]
logs attached
[vcd.log](https://github.com/vmware/container-service-extension/files/2716051/vcd.log)

**Comment by rocknes** [comment]
I ran the same set of commands on my vcd setup (v9.5) with api version set to 28.0. And the set of links I got in the Catalog XML is as follows,

    <Link rel="up" href="https://cloud.local/api/org/8f00ad55-9f9b-419e-a5a1-6e825ef60da5" type="application/vnd.vmware.vcloud.org+xml"/>
    <Link rel="down" href="https://cloud.local/api/catalog/a2dea8b8-a43e-4e1d-bcae-fb33805f5ddd/metadata" type="application/vnd.vmware.vcloud.metadata+xml"/>
    <Link rel="add" href="https://cloud.local/api/catalog/a2dea8b8-a43e-4e1d-bcae-fb33805f5ddd/catalogItems" type="application/vnd.vmware.vcloud.catalogItem+xml"/>
    <Link rel="add" href="https://cloud.local/api/catalog/a2dea8b8-a43e-4e1d-bcae-fb33805f5ddd/action/upload" type="application/vnd.vmware.vcloud.media+xml"/>
    <Link rel="add" href="https://cloud.local/api/catalog/a2dea8b8-a43e-4e1d-bcae-fb33805f5ddd/action/upload" type="application/vnd.vmware.vcloud.uploadVAppTemplateParams+xml"/>
    <Link rel="edit" href="https://cloud.local/api/admin/catalog/a2dea8b8-a43e-4e1d-bcae-fb33805f5ddd" type="application/vnd.vmware.vcloud.catalog+xml"/>
    <Link rel="remove" href="https://cloud.local/api/admin/catalog/a2dea8b8-a43e-4e1d-bcae-fb33805f5ddd"/>
    <Link rel="copy" href="https://cloud.local/api/catalog/a2dea8b8-a43e-4e1d-bcae-fb33805f5ddd/action/copy" type="application/vnd.vmware.vcloud.copyOrMoveCatalogItemParams+xml"/>
    <Link rel="move" href="https://cloud.local/api/catalog/a2dea8b8-a43e-4e1d-bcae-fb33805f5ddd/action/move" type="application/vnd.vmware.vcloud.copyOrMoveCatalogItemParams+xml"/>
    <Link rel="add" href="https://cloud.local/api/catalog/a2dea8b8-a43e-4e1d-bcae-fb33805f5ddd/action/captureVApp" type="application/vnd.vmware.vcloud.captureVAppParams+xml"/>
    <Link rel="publish" href="https://cloud.local/api/admin/catalog/a2dea8b8-a43e-4e1d-bcae-fb33805f5ddd/action/publish" type="application/vnd.vmware.admin.publishCatalogParams+xml"/>
    <Link rel="publishToExternalOrganizations" href="https://cloud.local/api/admin/catalog/a2dea8b8-a43e-4e1d-bcae-fb33805f5ddd/action/publishToExternalOrganizations" type="application/vnd.vmware.admin.publishExternalCatalogParams+xml"/>
    <Link rel="subscribeToExternalCatalog" href="https://cloud.local/api/admin/catalog/a2dea8b8-a43e-4e1d-bcae-fb33805f5ddd/action/subscribeToExternalCatalog" type="application/vnd.vmware.admin.externalCatalogSubscriptionParams+xml"/>
    <Link rel="down" href="https://cloud.local/api/catalog/a2dea8b8-a43e-4e1d-bcae-fb33805f5ddd/controlAccess/" type="application/vnd.vmware.vcloud.controlAccess+xml"/>
    <Link rel="controlAccess" href="https://cloud.local/api/catalog/a2dea8b8-a43e-4e1d-bcae-fb33805f5ddd/action/controlAccess" type="application/vnd.vmware.vcloud.controlAccess+xml"/>
    <Link rel="down" href="https://cloud.local/api/admin/catalog/a2dea8b8-a43e-4e1d-bcae-fb33805f5ddd/extension" type="application/vnd.vmware.admin.extensibility.selectors+xml"/>
    <Link rel="alternate" href="https://cloud.local/api/admin/catalog/a2dea8b8-a43e-4e1d-bcae-fb33805f5ddd" type="application/vnd.vmware.admin.catalog+xml"/>
    
In your case all the admin links i.e. links with url like /api/admin/... are missing. I am not sure what exactly is going on in here. Sys admin shouldn't have any issue seeing those links. I will deploy a 9.0.3 vCD testbed on monday and retry. It might be a vCD backward compatibility issue, that I am not able to reproduce the error with api v28.0.

Btw are you sure that the default sys admin is being used for cse installation (or the vcd-cli commands what I asked to run) and not some service account with a subset of sys admin rights?

**Comment by EvgBoor** [comment]
I use username with 'sys admin' right, i tested cse 1.2.5 on vcd 9.5, and all work perfectly!
