### ISSUE TITLE
CSE 1.2.5 does not work with VCD 8.20 version

### ISSUE THREAD

**Issue by Vijendrasi** [vmware/container-service-extension#189]
As per my observation VCD 8.20 is not able to recognize API commands from CSE 1.2.x version. 

After checking below mentioned file API version 27 is not mentioned which is supported API version in VCD 8.20 version.

"/usr/lib/python3.6/site-packages/pyvcloud/vcd/client.py

**Comment by rocknes** [comment]
The problem is not CSE 1.2.x but pycvloud, 8.20 is no longer a supported vCD version.

However cse can be forced to talk at api version 27.0 by providing 27.0 as value for the key *api_version* in the config file,

e.g. config file vcd section

vcd:
  api_version: '27.0'
  host: 'vcd fqdn'
  log: true
  password: 'supersecret'
  port: 443
  username: 'administrator'
  verify: false

Let us know if you still have issues.

**Comment by Vijendrasi** [comment]
It fails with below error. Same thing works with CSE 1.1 version.

root@photon-machine [ ~ ]# cse install --config $HOME/config.yaml
Validating config file '/root/config.yaml'
Connected to AMQP server (192.168.2.1:5672)
InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised.
Connected to vCloud Director (192.168.2.14:443)
Connected to vCenter Server 'vcsa65.lab65.local' as 'administrator@vsphere.local' (192.168.2.126:443)
Config file '/root/config.yaml' is valid
Installing CSE on vCloud Director using config file '/root/config.yaml'
Connected to vCD as system administrator: 192.168.2.14:443
Checking for AMQP exchange 'CSE'
AMQP exchange 'CSE' is ready
Traceback (most recent call last):
  File "/usr/bin/cse", line 11, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/container_service_extension/cse.py", line 227, in install
    amqp_install=amqp_install, ext_install=ext_install)
  File "/usr/lib/python3.6/site-packages/container_service_extension/config.py", line 495, in install_cse
    if should_configure_amqp(client, amqp, amqp_install):
  File "/usr/lib/python3.6/site-packages/container_service_extension/config.py", line 889, in should_configure_amqp
    diff_settings = [k for k, v in current_settings.items() if amqp[k] != v]
  File "/usr/lib/python3.6/site-packages/container_service_extension/config.py", line 889, in <listcomp>
    diff_settings = [k for k, v in current_settings.items() if amqp[k] != v]
KeyError: '{http://www.w3.org/2001/XMLSchema-instance}schemaLocation'

**Comment by rocknes** [comment]
Can you please upload the config file that you are using to install cse? And if possible the log file (cse.log) too.

Please feel free to redact ip, fqdn, username, password etc. in the config file.

**Comment by harshneelmore** [comment]
Hi @Vijendrasi,

Did vCD 8.20 work with CSE version 1.1.x?

**Comment by Vijendrasi** [comment]
Yes CSE 1.1 works with VCD 8.20. 
CSE supportability matrix updated after discussion by product team.
