### ISSUE TITLE
vcd 9.1.0.3 and cse 2.5 - installation ok, new cluster deployment error

### ISSUE THREAD

**Issue by pbosgraaf** [vmware/container-service-extension#209]
Hi!,
We've successfully installed CSE but i'm having issues continuing.
It looks like vcd cse extension has issues because all commands fail.
We run VCD 9.1.0.3 and CSE 2.5

[root@vcd01-cse ~]# vcd login vcd.hostname.com 501101 admin
Password:
admin logged in, org: '501101', vdc: ''
[root@vcd01-cse ~]# vcd vdc use "test-vdc"
now using org: '501101', vdc: 'test-vdc', vApp: ''.
[root@vcd01-cse. ~]#

After this i tried to create a new cluster, but every vcd cse command seems to fail:

[root@vcd01-cse ~]# vcd cse cluster create -n "10.201.68.244-254" mycluster
Usage: vcd cse cluster create [OPTIONS] NAME
Try "vcd cse cluster create -h" for help.

Error: Expecting value: line 1 column 1 (char 0)

[root@vcd01-cse.z00 ~]# vcd cse template list
Usage: vcd cse template list [OPTIONS]
Try "vcd cse template list -h" for help.

Error: Expecting value: line 1 column 1 (char 0)

[root@vcd01-cse ~]# vcd cse system info
Usage: vcd cse system info [OPTIONS]
Try "vcd cse system info -h" for help.

Error: Expecting value: line 1 column 1 (char 0)

[root@vcd01-cse ~]# cat .vcd-cli/profiles.yaml
active: default
extensions:
- container_service_extension.client.cse
profiles:
- api_version: '30.0'
  disable_warnings: false
  host: vcd.hostname.com
  log_body: true
  log_header: true
  log_request: true
  name: default
  org: '501101'
  org_href: https://vcd.hostname.com/api/org/67dc72f5-a5a7-4c36-8dd7-231e1201d796
  org_in_use: '501101'
  token: 9bf324aaa5e742fb938af4f62e7a71eb
  user: admin
  vapp_href: ''
  vapp_in_use: ''
  vdc_href: https://vcd.hostname.com/api/vdc/6f991535-b774-47a3-af0a-6847ef82d527
  vdc_in_use: test-vdc
  verify: true
  wkep:
    ADMIN: https://vcd.hostname.com/api/admin/
    API_EXTENSIBILITY: https://vcd.hostname.com/api/extensibility
    LOGGED_IN_ORG: https://vcd.hostname.com/api/org/67dc72f5-a5a7-4c36-8dd7-231e1201d796
    ORG_LIST: https://vcd.hostname.com/api/org/
    QUERY_LIST: https://vcd.hostname.com/api/query
[root@vcd01-cse ~]#

Looking at the vcd.log:

2019-01-28 13:33:37,899 | DEBUG | pyvcloud.vcd.cl | client          | _log_request | Request uri (POST): https://vcd.hostname.com/api/cse
2019-01-28 13:33:37,899 | DEBUG | pyvcloud.vcd.cl | client          | _log_request | Request headers: {'User-Agent': 'python-requests/2.21.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/*+json;version=30.0', 'Connection': 'keep-alive', 'x-vcloud-authorization': '9bf324aaa5e742fb938af4f62e7a71eb', 'Content-Length': '214'}
2019-01-28 13:33:37,899 | DEBUG | pyvcloud.vcd.cl | client          | _log_request | Request body: {"name": "k8cluster", "node_count": 2, "vdc": "test-vdc", "cpu": null, "memory": null, "network": "10.201.68.244-254", "storage_profile": null, "ssh_key": null, "template": null, "enable_nfs": false}
2019-01-28 13:33:37,900 | DEBUG | pyvcloud.vcd.cl | client          | _log_request | Response status code: 406
2019-01-28 13:33:37,900 | DEBUG | pyvcloud.vcd.cl | client          | _log_request | Response headers: {'Date': 'Mon, 28 Jan 2019 12:33:37 GMT', 'X-VMWARE-VCLOUD-REQUEST-ID': '8cc22ae1-f6c1-4fed-a2f6-54a3117c014f', 'X-VMWARE-VCLOUD-ACCESS-TOKEN': 'eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlzcyI6IjY3ZGM3MmY1LWE1YTctNGMzNi04ZGQ3LTIzMWUxMjAxZDc5NkBhZTZlY2FmMi03ZGU3LTRmZDQtOWUyMS05OTAxZDQxMmMxMzEiLCJleHAiOjE1NDg3NjQ1MDAsInZlcnNpb24iOiJ2Y2xvdWRfMS4wIiwianRpIjoiOWJmMzI0YWFhNWU3NDJmYjkzOGFmNGY2MmU3YTcxZWIifQ.qMJtv939iYvkPug5vDBc-zp6lFqUhyanBLUm27Y71NhPr8h_pCTtZF0kWTnP-PN9_WkDr-84rd_6cmgAUdg3yu5apDNinBVfnSkR_TWkB70t292UOrimBQ9O8u6827V2IdPtunUz7wWqFBdBu2ICUc2l05eIpjfhdwqkojc0Ph-jZv14UWDVcGOUmGrGzGz-E-MPRy7XZ0dvZmT7eW1rXuF_hckyBgp1xQ0lUemh9PzQg6-FXxTi4Z5JDRiXcLeRYC0WRgGfnn0kSUmROK4GAtHOq3vFpbiulQfauzDtzecPLDqMs142iK5V_DYtBAnO9Dahmj1oHqm2KRoU-zavow', 'X-VMWARE-VCLOUD-TOKEN-TYPE': 'Bearer', 'x-vcloud-authorization': '9bf324aaa5e742fb938af4f62e7a71eb', 'Content-Type': 'application/vnd.vmware.vcloud.error+xml;version=30.0', 'X-VMWARE-VCLOUD-REQUEST-EXECUTION-TIME': '36', 'Content-Length': '717'}
2019-01-28 13:33:37,900 | DEBUG | pyvcloud.vcd.cl | client          | _log_request | Response body: <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Error xmlns="http://www.vmware.com/vcloud/v1.5" xmlns:vmext="http://www.vmware.com/vcloud/extension/v1.5" xmlns:ovf="http://schemas.dmtf.org/ovf/envelope/1" xmlns:vssd="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData" xmlns:common="http://schemas.dmtf.org/wbem/wscim/1/common" xmlns:rasd="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData" xmlns:vmw="http://www.vmware.com/schema/ovf" xmlns:ovfenv="http://schemas.dmtf.org/ovf/environment/1" xmlns:ns9="http://www.vmware.com/vcloud/versions" majorErrorCode="406" message="json is not an acceptable media type." minorErrorCode="NOT_ACCEPTABLE"/>

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/container_service_extension/client/cse.py", line 257, in create
    enable_nfs=enable_nfs)
  File "/usr/lib/python3.6/site-packages/container_service_extension/client/cluster.py", line 134, in create_cluster
    return self._process_response(response)
  File "/usr/lib/python3.6/site-packages/container_service_extension/client/cluster.py", line 27, in _process_response
    content = json.loads(decoded)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

2019-01-28 13:33:58,545 | DEBUG | pyvcloud.vcd.cl | client          | _log_request | Request uri (GET): https://vcd.hostname.com/api/cse/system
2019-01-28 13:33:58,545 | DEBUG | pyvcloud.vcd.cl | client          | _log_request | Request headers: {'User-Agent': 'python-requests/2.21.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/*+json;version=30.0', 'Connection': 'keep-alive', 'x-vcloud-authorization': '9bf324aaa5e742fb938af4f62e7a71eb'}
2019-01-28 13:33:58,545 | DEBUG | pyvcloud.vcd.cl | client          | _log_request | Response status code: 406
2019-01-28 13:33:58,546 | DEBUG | pyvcloud.vcd.cl | client          | _log_request | Response headers: {'Date': 'Mon, 28 Jan 2019 12:33:58 GMT', 'X-VMWARE-VCLOUD-REQUEST-ID': '5290c236-81a9-4e39-bf6c-be6acb04c0cd', 'X-VMWARE-VCLOUD-ACCESS-TOKEN': 'eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlzcyI6IjY3ZGM3MmY1LWE1YTctNGMzNi04ZGQ3LTIzMWUxMjAxZDc5NkBhZTZlY2FmMi03ZGU3LTRmZDQtOWUyMS05OTAxZDQxMmMxMzEiLCJleHAiOjE1NDg3NjQ1MDAsInZlcnNpb24iOiJ2Y2xvdWRfMS4wIiwianRpIjoiOWJmMzI0YWFhNWU3NDJmYjkzOGFmNGY2MmU3YTcxZWIifQ.qMJtv939iYvkPug5vDBc-zp6lFqUhyanBLUm27Y71NhPr8h_pCTtZF0kWTnP-PN9_WkDr-84rd_6cmgAUdg3yu5apDNinBVfnSkR_TWkB70t292UOrimBQ9O8u6827V2IdPtunUz7wWqFBdBu2ICUc2l05eIpjfhdwqkojc0Ph-jZv14UWDVcGOUmGrGzGz-E-MPRy7XZ0dvZmT7eW1rXuF_hckyBgp1xQ0lUemh9PzQg6-FXxTi4Z5JDRiXcLeRYC0WRgGfnn0kSUmROK4GAtHOq3vFpbiulQfauzDtzecPLDqMs142iK5V_DYtBAnO9Dahmj1oHqm2KRoU-zavow', 'X-VMWARE-VCLOUD-TOKEN-TYPE': 'Bearer', 'x-vcloud-authorization': '9bf324aaa5e742fb938af4f62e7a71eb', 'Content-Type': 'application/vnd.vmware.vcloud.error+xml;version=30.0', 'X-VMWARE-VCLOUD-REQUEST-EXECUTION-TIME': '36', 'Content-Length': '717'}
2019-01-28 13:33:58,546 | DEBUG | pyvcloud.vcd.cl | client          | _log_request | Response body: <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Error xmlns="http://www.vmware.com/vcloud/v1.5" xmlns:vmext="http://www.vmware.com/vcloud/extension/v1.5" xmlns:ovf="http://schemas.dmtf.org/ovf/envelope/1" xmlns:vssd="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData" xmlns:common="http://schemas.dmtf.org/wbem/wscim/1/common" xmlns:rasd="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData" xmlns:vmw="http://www.vmware.com/schema/ovf" xmlns:ovfenv="http://schemas.dmtf.org/ovf/environment/1" xmlns:ns9="http://www.vmware.com/vcloud/versions" majorErrorCode="406" message="json is not an acceptable media type." minorErrorCode="NOT_ACCEPTABLE"/>

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/container_service_extension/client/cse.py", line 535, in info
    result = system.get_info()
  File "/usr/lib/python3.6/site-packages/container_service_extension/client/system.py", line 47, in get_info
    return self._process_response(response)
  File "/usr/lib/python3.6/site-packages/container_service_extension/client/system.py", line 24, in _process_response
    content = json.loads(decoded)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

I found this issue which seems to had similar problems but no answer
https://github.com/vmware/container-service-extension/issues/84

Any tips?

**Comment by andrew-ni** [comment]
This error message usually occurs when vCD responds with an empty XML body when the CSE service is down or not configured properly. CSE expects a JSON response and does not output a helpful error message here (known issue, similar to #196).

I suspect that this is due to either the server not running, or CSE not being correctly registered to vCD. 

- Can you verify that CSE server is running? `cse run -c config.yaml`

- You can do a clean registration of CSE to vCD by running these commands:
```
# login as system administrator to vCD

# delete CSE from vCD
$ vcd system extension delete cse

# re-install CSE (since templates exist already, this will only register CSE as an extension to vCD)
$ cse install -c config.yaml -ext-install config
```

- Another issue could be that the AMQP server is not communicating to vCD correctly. Please verify the AMQP connection with vCD via vCD web ui, and verify that the amqp settings in the config file are the same (except for `exchange`, which should be exclusive to CSE).

Please let me know if CSE works after this, and if it doesn't, we'll do some further investigation.

**Comment by andrew-ni** [comment]
I'm able to reproduce this issue. This appears when CSE is not registered, or is not properly registered to vCD. Please see the above post to redo the registration step of CSE installation.

This issue usually results from CSE installation not validating the CSE extension on vCD if it already exists. We should check the properties of the CSE extension on vCD if we find that it exists.

Pull request #206 fixes this issue

**Comment by pbosgraaf** [comment]
Thanks for the quick response! It was an amqp issue in combination with my interpretation of the exchange topic/direct workaround mentioned in another thread.

I thought changing it to something exclusive for CSE was just to workaround the installer errorr, so i changed it back to the vcd values every time the installer finished. This was the problem, leaving it at exchange dedicated for CSE fixed the issue.

Everything is working now, thanks!
