### ISSUE TITLE
"{cse}:CSE NATIVE DEPLOY RIGHT" already exist

### ISSUE THREAD

**Issue by vchrisst** [vmware/container-service-extension#266]
Hi,

I recently played around with the CSE. Some of my test was to delete everything from my vCloud. 
Now when I try to reactivate the Installation I got an error:

`vchrisst@ubuntu-vdi-001:~$ cse install -u -c config.yaml --ssh-key ~/.ssh/id_rsa.pub
Validating config file 'config.yaml'
Connected to AMQP server (172.16.6.117:5672)
InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised.
Connected to vCloud Director (172.16.6.104:443)
Connected to vCenter Server 'VCD-VC' as 'administrator@vcd.local' (172.16.6.103:443)
Config file 'config.yaml' is valid
Installing CSE on vCloud Director using config file 'config.yaml'
Connected to vCD as system administrator: 172.16.6.104:443
Checking for AMQP exchange 'vcloud'
AMQP exchange 'vcloud' is ready
CSE is registered to vCD and has same settings as config file
CSE Installation Error. Check CSE install logs
Traceback (most recent call last):
  File "/home/vchrisst/.local/bin/cse", line 11, in <module>
    sys.exit(cli())
  File "/home/vchrisst/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/vchrisst/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/vchrisst/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vchrisst/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vchrisst/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/vchrisst/.local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/vchrisst/.local/lib/python3.6/site-packages/container_service_extension/cse.py", line 239, in install
    ext_install=ext_install)
  File "/home/vchrisst/.local/lib/python3.6/site-packages/container_service_extension/configure_cse.py", line 686, in install_cse
    bundle_key=CSE_NATIVE_DEPLOY_RIGHT_BUNDLE_KEY)
  File "/home/vchrisst/.local/lib/python3.6/site-packages/container_service_extension/configure_cse.py", line 1241, in register_right
    raise err
  File "/home/vchrisst/.local/lib/python3.6/site-packages/container_service_extension/configure_cse.py", line 1227, in register_right
    bundle_key)
  File "/home/vchrisst/.local/lib/python3.6/site-packages/pyvcloud/vcd/api_extension.py", line 326, in add_service_right
    params)
  File "/home/vchrisst/.local/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 1170, in post_linked_resource
    media_type)
  File "/home/vchrisst/.local/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 1154, in post_resource
    objectify_results=objectify_results)
  File "/home/vchrisst/.local/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 941, in _do_request
    _objectify_response(response, objectify_results))
  File "/home/vchrisst/.local/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 946, in _response_code_to_exception
    raise BadRequestException(sc, request_id, objectify_response)
pyvcloud.vcd.exceptions.BadRequestException: Status code: 400/BAD_REQUEST, [ a90add4f-b0c7-465c-a6e8-55a22a37e4dd ] Ein Recht mit dem Namen "{cse}:CSE NATIVE DEPLOY RIGHT" ist bereits vorhanden. Ein Recht mit demselben Namen kann nicht hinzugefügt werden. (request id: a90add4f-b0c7-465c-a6e8-55a22a37e4dd)
`

When I login to my vCloud and lokk at the right the CSE rights are not there. Neither in System nor in an Organisation.

`vchrisst@ubuntu-vdi-001:~$ vcd login 172.16.6.105 System administrator -i -w
Password:
administrator logged in, org: 'System', vdc: ''
vchrisst@ubuntu-vdi-001:~$ vcd right list |grep cse
vchrisst@ubuntu-vdi-001:~$`

Already rebooted my Client and the vCD Cells without any success.

**Comment by rocknes** [comment]
I think the following check is not triggering since the check assumes the error message to be in English, while in your case the error message is in German.

https://github.com/vmware/container-service-extension/blob/bac8df19d0397644149a81e1bd6078542a15b519/container_service_extension/configure_cse.py#L1171
To fix this issue, we will need a code change. 

I am surprised that the right is not showing up in any org. Can you please,
1. Log into vCD Flex ui as sys admin,
2. Navigate to the administration tab
3. Click on the Role section (on the left)
4. Try to add a new role.
   a. From the drop down select System org.
   b. In the list of rights, scroll down and check if you have a section for cse, if yes, then expand it and check if you have the right {cse}:CSE NATIVE DEPLOY RIGHT or not.

**Comment by vchrisst** [comment]
Hi,


also in the GUI the right is not visible. 

![vCD-Rights](https://user-images.githubusercontent.com/12514073/54071190-99274e00-4269-11e9-8211-7abf1eefae79.jpg)

**Comment by rocknes** [comment]
Generally the cse rights are towards the bottom of the list (the list is not sorted).
![Screenshot 2019-03-11 14 10 13](https://user-images.githubusercontent.com/4933668/54158359-995d5000-4407-11e9-9877-98b92d786528.png)

**Comment by rocknes** [comment]
I just discovered that the rights can exist in vCD and not be assigned to system org.

Can you run the following as sys admin 
>vcd right info "{cse}:CSE NATIVE DEPLOY RIGHT"

If you get back a result, it means that the right in vCD.
However if the following command doesn't yield a result, it means System org is not granted the right.
>vcd right list | grep "{cse}:CSE NATIVE DEPLOY RIGHT"

This doesn't solve your immediate problem but atleast explains why we are not seeing the right in the UI but our effort to register the right fails.

**Comment by rocknes** [comment]
FYI: I have added a fix for this, it will available in next CSE release
https://reviewable.io/reviews/vmware/container-service-extension/267#-

**Comment by vchrisst** [comment]
Hi,

the first checks gives a response so you are right.
Thanks for your support and I will wait for the next release
