### ISSUE TITLE
Cluster deployment fails with "VM is not ready to execute scripts" - CSE 1.2.7

### ISSUE THREAD

**Issue by Hjelmar** [vmware/container-service-extension#284]
Hi

 

For the last few days, I have tried to set up CSE on vCD. And all in all it has been quite straight forward.

 
I am running into an issue though I was hoping someone has seen before .

We are using CSE 1.2.7 and vCD9.5

Cluster and master node is being created in vCD - but fails in the "initializing cluster" part where it aparently should run customization scripts with the error: Unable to execute scripts.

 
I looks like vmtools are running as per line 2 - but still not able to run the scripts.

 
when creating the cluster with vcd-cli :
![Capture](https://user-images.githubusercontent.com/48988252/55214944-68975c00-51f8-11e9-8c02-fde994823989.JPG)

 

From cse-debug-log:

 

19-03-27 12:14:13 | cluster:225 - wait_for_tools_ready_callback | DEBUG :: waiting for guest tools, status: vm='vim.VirtualMachine:vm-5869', status=guestToolsNotRunning

19-03-27 12:14:18 | cluster:225 - wait_for_tools_ready_callback | DEBUG :: waiting for guest tools, status: vm='vim.VirtualMachine:vm-5869', status=**guestToolsRunning**

19-03-27 12:14:34 | cluster:231 - wait_for_guest_execution_callback | DEBUG :: waiting for process 1224 on vm 'vim.VirtualMachine:vm-5869' to finish (1)

19-03-27 12:14:40 | cluster:231 - wait_for_guest_execution_callback | DEBUG :: process [0, <Response [200]>, <Response [200]>] on vm 'vim.VirtualMachine:vm-5869' finished, exit code: 0

19-03-27 12:14:40 | cluster:363 - execute_script_in_nodes | DEBUG :: about to execute script on mstr-bu7s (vm='vim.VirtualMachine:vm-5869'), wait=False

19-03-27 12:14:40 | cluster:390 - execute_script_in_nodes | DEBUG :: [1230]

19-03-27 12:14:40 | cluster:391 - execute_script_in_nodes | DEBUG ::

19-03-27 12:14:40 | cluster:392 - execute_script_in_nodes | DEBUG ::

19-03-27 12:14:40 | cluster:352 - execute_script_in_nodes | DEBUG :: will try to execute script on mstr-bu7s:

#!/usr/bin/env bash

set -e

while [ `systemctl is-active docker` != 'active' ]; do echo 'waiting for docker'; sleep 5; done

kubeadm init --kubernetes-version=v1.10.11 > /root/kubeadm-init.out

mkdir -p /root/.kube

cp -f /etc/kubernetes/admin.conf /root/.kube/config

chown $(id -u):$(id -g) /root/.kube/config

kubectl apply -f /root/weave.yml

 

 

19-03-27 12:14:40 | cluster:358 - execute_script_in_nodes | DEBUG :: waiting for tools on mstr-bu7s

19-03-27 12:14:40 | cluster:225 - wait_for_tools_ready_callback | DEBUG :: waiting for guest tools, status: vm='vim.VirtualMachine:vm-5869', status=guestToolsRunning

19-03-27 12:14:42 | cluster:331 - wait_until_ready_to_exec | INFO :: VM is not ready to execute scripts, yet

19-03-27 12:14:47 | cluster:331 - wait_until_ready_to_exec | INFO :: VM is not ready to execute scripts, yet

19-03-27 12:14:51 | cluster:331 - wait_until_ready_to_exec | INFO :: VM is not ready to execute scripts, yet

19-03-27 12:14:55 | cluster:331 - wait_until_ready_to_exec | INFO :: VM is not ready to execute scripts, yet

19-03-27 12:14:59 | cluster:331 - wait_until_ready_to_exec | INFO :: VM is not ready to execute scripts, yet

19-03-27 12:15:04 | cluster:331 - wait_until_ready_to_exec | INFO :: VM is not ready to execute scripts, yet

19-03-27 12:15:07 | cluster:331 - wait_until_ready_to_exec | INFO :: VM is not ready to execute scripts, yet

19-03-27 12:15:11 | cluster:331 - wait_until_ready_to_exec | INFO :: VM is not ready to execute scripts, yet

19-03-27 12:15:16 | cluster:331 - wait_until_ready_to_exec | INFO :: VM is not ready to execute scripts, yet

19-03-27 12:15:20 | cluster:331 - wait_until_ready_to_exec | INFO :: VM is not ready to execute scripts, yet

19-03-27 12:15:24 | cluster:331 - wait_until_ready_to_exec | INFO :: VM is not ready to execute scripts, yet

19-03-27 12:15:29 | cluster:331 - wait_until_ready_to_exec | INFO :: VM is not ready to execute scripts, yet

19-03-27 12:15:33 | cluster:331 - wait_until_ready_to_exec | INFO :: VM is not ready to execute scripts, yet

19-03-27 12:15:37 | cluster:331 - wait_until_ready_to_exec | INFO :: VM is not ready to execute scripts, yet

19-03-27 12:15:42 | cluster:331 - wait_until_ready_to_exec | INFO :: VM is not ready to execute scripts, yet

19-03-27 12:15:45 | cluster:331 - wait_until_ready_to_exec | INFO :: VM is not ready to execute scripts, yet

19-03-27 12:15:50 | cluster:331 - wait_until_ready_to_exec | INFO :: VM is not ready to execute scripts, yet

19-03-27 12:15:54 | cluster:331 - wait_until_ready_to_exec | INFO :: VM is not ready to execute scripts, yet

19-03-27 12:15:59 | cluster:331 - wait_until_ready_to_exec | INFO :: VM is not ready to execute scripts, yet

19-03-27 12:16:02 | cluster:331 - wait_until_ready_to_exec | INFO :: VM is not ready to execute scripts, yet

19-03-27 12:16:07 | cluster:331 - wait_until_ready_to_exec | INFO :: VM is not ready to execute scripts, yet

19-03-27 12:16:12 | cluster:331 - wait_until_ready_to_exec | INFO :: VM is not ready to execute scripts, yet

19-03-27 12:16:16 | cluster:331 - wait_until_ready_to_exec | INFO :: VM is not ready to execute scripts, yet

19-03-27 12:16:20 | cluster:331 - wait_until_ready_to_exec | INFO :: VM is not ready to execute scripts, yet

19-03-27 12:16:24 | cluster:331 - wait_until_ready_to_exec | INFO :: VM is not ready to execute scripts, yet

19-03-27 12:16:28 | cluster:331 - wait_until_ready_to_exec | INFO :: VM is not ready to execute scripts, yet

19-03-27 12:16:32 | cluster:331 - wait_until_ready_to_exec | INFO :: VM is not ready to execute scripts, yet

19-03-27 12:16:37 | cluster:331 - wait_until_ready_to_exec | INFO :: VM is not ready to execute scripts, yet

19-03-27 12:16:41 | cluster:331 - wait_until_ready_to_exec | INFO :: VM is not ready to execute scripts, yet

19-03-27 12:16:45 | cluster:331 - wait_until_ready_to_exec | INFO :: VM is not ready to execute scripts, yet

19-03-27 12:16:47 | broker:535 - create_cluster_thread | ERROR :: Traceback (most recent call last):

  File "/home/cseadmin/.local/lib/python3.6/site-packages/container_service_extension/broker.py", line 479, in create_cluster_thread

    init_cluster(server_config, vapp, template)

  File "/home/cseadmin/.local/lib/python3.6/site-packages/container_service_extension/cluster.py", line 282, in init_cluster

    script, nodes)

  File "/home/cseadmin/.local/lib/python3.6/site-packages/container_service_extension/cluster.py", line 361, in execute_script_in_nodes

    wait_until_ready_to_exec(vs, vm, password)

  File "/home/cseadmin/.local/lib/python3.6/site-packages/container_service_extension/cluster.py", line 334, in wait_until_ready_to_exec

    raise CseServerError('VM is not ready to execute scripts')

container_service_extension.exceptions.CseServerError: **VM is not ready to execute scripts**

**Comment by Hjelmar** [comment]
Aparently this is only an issue when using the PhotonOS template - Ubuntu template deploys just fine...

**Comment by Hjelmar** [comment]
Seems to be a buggy PhotonOS template. Closing the issue :)
