### ISSUE TITLE
cse run without -s sometime generates timeout on amqp

### ISSUE THREAD

**Issue by pacogomez** [vmware/container-service-extension#52]
Traceback (most recent call last):
  File "/Users/pgomez/.virtualenvs/cse/bin/cse", line 10, in <module>
    sys.exit(cli())
  File "/Users/pgomez/.virtualenvs/cse/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/pgomez/.virtualenvs/cse/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/pgomez/.virtualenvs/cse/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/pgomez/.virtualenvs/cse/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/pgomez/.virtualenvs/cse/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/pgomez/.virtualenvs/cse/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/pgomez/vmware/container-service-extension/container_service_extension/cse.py", line 103, in run
    service.run()
  File "/Users/pgomez/vmware/container-service-extension/container_service_extension/service.py", line 44, in run
    self.config = check_config(self.config_file)
  File "/Users/pgomez/vmware/container-service-extension/container_service_extension/config.py", line 113, in check_config
    connection = pika.BlockingConnection(parameters)
  File "/Users/pgomez/.virtualenvs/cse/lib/python3.6/site-packages/pika-0.11.0-py3.6.egg/pika/adapters/blocking_connection.py", line 374, in __init__
  File "/Users/pgomez/.virtualenvs/cse/lib/python3.6/site-packages/pika-0.11.0-py3.6.egg/pika/adapters/blocking_connection.py", line 414, in _process_io_for_connection_setup
  File "/Users/pgomez/.virtualenvs/cse/lib/python3.6/site-packages/pika-0.11.0-py3.6.egg/pika/adapters/blocking_connection.py", line 468, in _flush_output
pika.exceptions.ConnectionClosed: Connection to 10.150.199.8:5672 failed: timeout

**Comment by sakthisunda** [comment]
This exact exception happens only when the AMQP server is down or getting powered on, and cse server run happens at the same time. Otherwise, a clean connection happens always when AMQP server is on.
