### ISSUE TITLE
CSE 2.6.0.0b1 & vCD 10.1 beta: Error creating the photon-v2_k8-1.14_weave-2.5.2_rev2 template

### ISSUE THREAD

**Issue by m1gu3lg** [vmware/container-service-extension#533]
When attempting the CSE 2.6.0.0b1 installation in vCD 10.1 beta, I am getting an error when trying to create the photon-v2_k8-1.14_weave-2.5.2_rev2 template. The CSE installation log reports the following:
```
20-02-26 14:27:05 | template_builder:217 - _create_temp_vapp | INFO :: Creating vApp 'photon-v2_k8-1.14_weave-2.5.2_temp'

20-02-26 14:27:07 | configure_cse:356 - install_cse | ERROR :: CSE Installation Error

Traceback (most recent call last):

  File "/usr/local/lib/python3.7/site-packages/container_service_extension/configure_cse.py", line 301, in install_cse

    msg_update_callback=msg_update_callback)

  File "/usr/local/lib/python3.7/site-packages/container_service_extension/configure_cse.py", line 686, in _install_template

    retain_temp_vapp=retain_temp_vapp)

  File "/usr/local/lib/python3.7/site-packages/container_service_extension/template_builder.py", line 447, in build

    vapp = self._create_temp_vapp()

  File "/usr/local/lib/python3.7/site-packages/container_service_extension/template_builder.py", line 236, in _create_temp_vapp

    storage_profile=self.storage_profile)

  File "/usr/local/lib/python3.7/site-packages/pyvcloud/vcd/vdc.py", line 465, in instantiate_vapp

    vapp_template_params)

  File "/usr/local/lib/python3.7/site-packages/pyvcloud/vcd/client.py", line 1426, in post_linked_resource

    media_type)

  File "/usr/local/lib/python3.7/site-packages/pyvcloud/vcd/client.py", line 1410, in post_resource

    params=params)

  File "/usr/local/lib/python3.7/site-packages/pyvcloud/vcd/client.py", line 1169, in _do_request

    _objectify_response(response, objectify_results))

  File "/usr/local/lib/python3.7/site-packages/pyvcloud/vcd/client.py", line 1206, in _response_code_to_exception

    raise InternalServerException(sc, request_id, objectify_response)

pyvcloud.vcd.exceptions.InternalServerException: Status code: 500/INTERNAL_SERVER_ERROR, [ ba377fef-9245-4c7a-b718-e0b1f3cde131 ] class java.lang.NullPointerException (request id: ba377fef-9245-4c7a-b718-e0b1f3cde131)
```
All the Ubuntu templates have been generated with no issues. I have been able to manually deploy a vApp with the photon-custom-hw11-2.0-304b817.ova vApp template that has been uploaded to the vCD 10.1 CSE catalog with no issues.

**Comment by m1gu3lg** [comment]
[cse-install_2020-02-28_08-53-29.log](https://github.com/vmware/container-service-extension/files/4265929/cse-install_2020-02-28_08-53-29.log)

**Comment by m1gu3lg** [comment]
[vcd10.1_logs.zip](https://github.com/vmware/container-service-extension/files/4265988/vcd10.1_logs.zip)

**Comment by andrew-ni** [comment]
@m1gu3lg this looks like a vCD issue that we've experienced before with the photon templates. I've sent a message to the vCD team to confirm that this is the same issue. I think this should already have been fixed in a recent build, but i'll let you know once they get back to me.

Could you also share your entire vCD version including the build number? (in the 'About' section in vCD)

**Comment by m1gu3lg** [comment]
@andrew-ni , I'm using VMware Cloud Director version: 10.1.0.15560706 Fri Jan 31 23:18:07 UTC 2020

**Comment by andrew-ni** [comment]
@m1gu3lg , I've confirmed with the vCD team that this is a bug found in some 10.1 builds. The build i'm using right now does now have the bug, and I can create all our templates.

my build: VMware Cloud Director version: 10.1.0.15716945 Wed Feb 26 06:45:21 UTC 2020

**Comment by m1gu3lg** [comment]
Thanks @andrew-ni. We will verify it when we install a new 10.1 beta build or the GA version.
Is this issue also present when using CSE 2.6 on vCD 10.0.0.1?

**Comment by rocknes** [comment]
Hi,

No, I don't think the issue is present in vCD 10.0.0.1.

Regards
Aritra Sen
