### ISSUE TITLE
Ubuntu template preparation - vmtools timeout / dpkg issue

### ISSUE THREAD

**Issue by jondwaite** [vmware/container-service-extension#73]
Attempting to refresh Ubuntu-16.04 template envountering the following (reproduced issue on 2 different CSE installs so reasonably sure this is a scripting error):

Command: `cse install --config config.yaml --template ubuntu-16.04 --update --amqp skip --ext skip`

During the block (where the 'waiting to finish x is incrementing each repeat):
```
:::
Customizing vApp template 'ubuntu1604-temp'
Attempt #1
waiting for guest tools, status: vm='vim.VirtualMachine:vm-168', status=guestToolsNotRunning
waiting for guest tools, status: vm='vim.VirtualMachine:vm-168', status=guestToolsRunning
waiting for process 1299 on vm 'vim.VirtualMachine:vm-168' to finish (x)
:::
```

Get to a point where the following error is displayed:

```
exception, will retry in a few seconds, vm 'vim.VirtualMachine:vm-168'
  exception: (vim.fault.GuestOperationsUnavailable) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'The guest operations agent could not be contacted.',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) []
}
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/vsphere_guest_run/vsphere.py", line 86, in execute_program_in_guest
    processes = pm.ListProcessesInGuest(vm, creds, [pid])
  File "/usr/lib/python3.6/site-packages/pyVmomi/VmomiSupport.py", line 580, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/usr/lib/python3.6/site-packages/pyVmomi/VmomiSupport.py", line 386, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/usr/lib/python3.6/site-packages/pyVmomi/SoapAdapter.py", line 1366, in InvokeMethod
    raise obj # pylint: disable-msg=E0702
pyVmomi.VmomiSupport.vim.fault.GuestOperationsUnavailable: (vim.fault.GuestOperationsUnavailable) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'The guest operations agent could not be contacted.',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) []
}
```
This repeats every 5 seconds or so. If left alone after 5 attempts the customization will fail completely.

Logging in to the template VM and forcing dpkg reconfigure and reinstall of open-vm-tools allows the customization to complete successfully:

```
root@ubuntu1604-temp:~# apt install open-vm-tools
E: dpkg was interrupted, you must manually run 'dpkg --configure -a' to correct the problem.
root@ubuntu1604-temp:~# dpkg --configure -a
Setting up python-apt-common (1.1.0~beta1ubuntu0.16.04.1) ...
Setting up cloud-guest-utils (0.27-0ubuntu25) ...
Setting up libapt-inst2.0:amd64 (1.2.25) ...
:::
Processing triggers for initramfs-tools (0.122ubuntu8.10) ...
update-initramfs: Generating /boot/initrd.img-4.4.0-116-generic
W: mdadm: /etc/mdadm/mdadm.conf defines no arrays.
Processing triggers for shim-signed (1.33.1~16.04.1+13-0ubuntu2) ...
No DKMS packages installed: not changing Secure Boot validation state.
Errors were encountered while processing:
 open-vm-tools

root@ubuntu1604-temp:~# apt install open-vm-tools
Reading package lists... Done
Building dependency tree
Reading state information... Done
Suggested packages:
  open-vm-tools-desktop
The following packages will be upgraded:
  open-vm-tools
1 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
1 not fully installed or removed.
Need to get 0 B/432 kB of archives.
After this operation, 0 B of additional disk space will be used.
(Reading database ... 82065 files and directories currently installed.)
Preparing to unpack .../open-vm-tools_2%3a10.0.7-3227872-5ubuntu1~16.04.2_amd64.deb ...
Unpacking open-vm-tools (2:10.0.7-3227872-5ubuntu1~16.04.2) over (2:10.0.7-3227872-5ubuntu1~16.04.1) ...
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Processing triggers for systemd (229-4ubuntu21.1) ...
Processing triggers for ureadahead (0.100.0-19) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up open-vm-tools (2:10.0.7-3227872-5ubuntu1~16.04.2) ...

Configuration file '/etc/vmware-tools/tools.conf'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** tools.conf (Y/I/N/O/D/Z) [default=N] ? Y
Installing new version of config file /etc/vmware-tools/tools.conf ...
Processing triggers for libc-bin (2.23-0ubuntu10) ...

```

Once the next customization attempt starts after fixing open-vm-tools the customization completes successfully and the template VM is powered off and imported successfully as usual.

It looks like something is causing a reboot during the package installation which is halting/corrupting the process?

**Comment by pacogomez** [comment]
Thanks Jon, we'll take a look
