### ISSUE TITLE
VCD CSE commands failing

### ISSUE THREAD

**Issue by whitecj87** [vmware/container-service-extension#84]
I recently installed CSE on a Centos 7 VM and configured it according to the install guide, version 1.0.0.  I was able to successfully configure the CSE extension with our vCloud Director 9.1 instance and have two templates loaded, photon-v2 and ubuntu-1604.  Finally, I configured CSE to run and start as a service on the VM and that seems to be working as intended.  

Unfortunately, now I am unable to issue any vcd cse commands, despite the profiles.yaml file being configured per the documentation.  I've attached screenshots showing the errors occurring, as well as screenshots of the various commands failing.  

![cse_templatelist_error](https://user-images.githubusercontent.com/40070793/41292025-520e448e-6e1f-11e8-82ab-8c32bab5fc56.PNG)
![cse_system_error](https://user-images.githubusercontent.com/40070793/41292029-542f9506-6e1f-11e8-9160-1c56be0c48b1.PNG)
![config_success](https://user-images.githubusercontent.com/40070793/41292031-559916b0-6e1f-11e8-92df-d4ac9ff3dfc8.PNG)

**Comment by tsugliani** [comment]
It seems the cse service isn't running, can you try to run it and try again ?

**Comment by whitecj87** [comment]
The service is running.  I get the same result whether I'm running the commands from the VM with CSE installed or as a test "tenant".

![servicerunning](https://user-images.githubusercontent.com/40070793/41295551-d78439bc-6e28-11e8-8c0a-277abb9506b1.PNG)

**Comment by whitecj87** [comment]
Thanks Timo, here's the vcd.log file.  Do you need the cse.log file as well?

[vcd.log](https://github.com/vmware/container-service-extension/files/2094653/vcd.log)

**Comment by evanchsa** [comment]
It looks like the '~/.vcd-cli/profiles.yaml' file could not be opened.

Warning: the profiles file '~/.vcd-cli/profiles.yaml' could not be open. Using default values.

It also looks like the Virtual Datacenter was not set which is why the command is not working.

**Comment by whitecj87** [comment]
Thanks Stephen, if you look down toward the end of the file, you'll see the more current alarms.  I've been just trying to run vcd cse system info and getting errors in return.  The profiles.yaml file issues were corrected earlier today and the permissions are set correctly to my eye.  What I'm seeing in particular is:
`Traceback (most recent call last):
  File "/home/<uname>/.local/lib/python3.6/site-packages/container_service_extension/client/cse.py", line 458, in info
    result = system.get_info()
  File "/home/<uname>/.local/lib/python3.6/site-packages/container_service_extension/client/system.py", line 47, in get_info
    return self._process_response(response)
  File "/home/<uname>/.local/lib/python3.6/site-packages/container_service_extension/client/system.py", line 24, in _process_response
    content = json.loads(decoded)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Traceback (most recent call last):
  File "/home/<uname>/.local/lib/python3.6/site-packages/container_service_extension/client/cse.py", line 458, in info
    result = system.get_info()
  File "/home/<uname>/.local/lib/python3.6/site-packages/container_service_extension/client/system.py", line 47, in get_info
    return self._process_response(response)
  File "/home/<uname>/.local/lib/python3.6/site-packages/container_service_extension/client/system.py", line 24, in _process_response
    content = json.loads(decoded)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Traceback (most recent call last):
  File "/home/<uname>/.local/lib/python3.6/site-packages/container_service_extension/client/cse.py", line 121, in list_templates
    templates = cluster.get_templates()
  File "/home/<uname>/.local/lib/python3.6/site-packages/container_service_extension/client/cluster.py", line 52, in get_templates
    return self._process_response(response)
  File "/home/<uname>/.local/lib/python3.6/site-packages/container_service_extension/client/cluster.py", line 27, in _process_response
    content = json.loads(decoded)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by tsugliani** [comment]
I see a lot of errors on certificates

``` 
Traceback (most recent call last):
  File "/home/<uname>/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/<uname>/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/home/<uname>/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/home/<uname>/.local/lib/python3.6/site-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/home/<uname>/.local/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib64/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib64/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)
```

So that doesn't look good, yes please share the `cse.log` file too.

**Comment by whitecj87** [comment]
Thank you guys for all the help.  Here is the cse.log as well.  

[cse.log](https://github.com/vmware/container-service-extension/files/2094741/cse.log)

**Comment by sahithi** [comment]
Run "vcd login" command using orgadmin not sysadmin. Try this and see if it helps.
I am busy with other tasks right now and give me sometime before I take look into your logs

**Comment by whitecj87** [comment]
Thanks sahithi, I tried that from another system but unfortunately it didn't seem to help.   I logged in  using my test org and org admin creds but still wasn't able to run any vcd cse commands except vcd cse version.  I've attached the vcd.log file here.  

[vcd.log](https://github.com/vmware/container-service-extension/files/2103799/vcd.log)

**Comment by sahithi** [comment]
As mentioned in previous comments, can you check if virtual datacenter is selected for a given org?

**Comment by sompa** [comment]
Closing due to inactivity. Feel free to reopen the issue if there is any further need.
