### ISSUE TITLE
vCenter 6.7 problem

### ISSUE THREAD

**Issue by furyflash777** [vmware/container-service-extension#92]
Hello.
I am  trying to install the CSE, but have an error with SSL. 
curl gets response from the vcenter as well. 

# /root/.local/bin/cse check --config /root/config.yaml

Validating CSE on vCD from file: /root/config.yaml
Python version >= 3.6 (installed: 3.6.5): success
Connected to AMQP server (xxxamqp1.local:5673): success
Connected to vCloud Director as system administrator (vcd.xxx.xxx:443): success
Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/container_service_extension/cse.py", line 111, in check
    check_config(config, template)
  File "/root/.local/lib/python3.6/site-packages/container_service_extension/config.py", line 205, in check_config
    v.connect()
  File "/root/.local/lib/python3.6/site-packages/vsphere_guest_run/vsphere.py", line 32, in connect
    sslContext=context)
  File "/root/.local/lib/python3.6/site-packages/pyVim/connect.py", line 836, in SmartConnect
    sslContext)
  File "/root/.local/lib/python3.6/site-packages/pyVim/connect.py", line 718, in __FindSupportedVersion
    sslContext)
  File "/root/.local/lib/python3.6/site-packages/pyVim/connect.py", line 638, in __GetServiceVersionDescription
    path + "/vimServiceVersions.xml", sslContext)
  File "/root/.local/lib/python3.6/site-packages/pyVim/connect.py", line 604, in __GetElementTree
    conn.request("GET", path)
  File "/usr/lib64/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/lib64/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/usr/lib64/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib64/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:833)

The configuration is invalid, EOF occurred in violation of protocol (_ssl.c:833). See 'cse.log' for details

**Comment by tsugliani** [comment]
Hi @furyflash777,

Yes I've notified the @pacogomez that this is currently an issue.
/cc @sahithi for my analysis.

Basically this is what is called

https://github.com/vmware/container-service-extension/blob/master/container_service_extension/config.py#L203-L205

Here it seems we are not using any config element for the `verify: false` in the yaml (that's not the direct issue)

The actual issue is depicted here:

https://github.com/vmware/vsphere-guest-run/blob/master/vsphere_guest_run/vsphere.py#L17-L32

Currently is forces TLSv1 which vSphere 6.7 does not support for various security reasons.

`context = ssl.SSLContext(ssl.PROTOCOL_TLSv1)`

If you want a quick & dirty fix for testing the solution you can just modify line 25 of that file (https://github.com/vmware/vsphere-guest-run/blob/master/vsphere_guest_run/vsphere.py#L25)

to 

`context = ssl._create_unverified_context()`

Warning this is basically the verify/false option active.

Hope this helps and it will be fixed soon :-)

**Comment by furyflash777** [comment]
Hi @tsugliani.
Thank you for help. Now it is working.

**Comment by sahithi** [comment]
@pacogomez  is currently work on the permanent fix. Will update once it is done.
