### ISSUE TITLE
Can not create new cluster: CSE 3.0.1, Python 3.8.5 

### ISSUE THREAD

**Issue by work423** [vmware/container-service-extension#970]
Hello.
Can not create cluster. 
VMware Cloud Director version: 10.2.0.17008054
CSE 3.0.1, Python 3.8.5 running on (Ubuntu 20.04)
Failed to create Native Cluster

Cloud director Error:
Couldn't initialize cluster: Error executing script in node mstr-mbch: <module 'container_service_extension.exceptions' from '/usr/local/lib/python3.8/dist-packages/container_service_extension/exceptions.py'>

**Comment by jkfletch02** [comment]
Could you please include the error output from your cse-logs/cse-install/server log file?

**Comment by work423** [comment]
Output: .cse-logs/cse-server-debug.log

21-03-25 12:59:00 | cluster_service:1816 - _wait_for_tools_ready_callback | Request Id: 330dce53-fd0b-4bcd-9eb6-31bc23cd185f | DEBUG :: waiting for guest tools, status: vm='vim.VirtualMachi                                                ne:vm-325974', status=guestToolsRunning
21-03-25 13:00:01 | cluster_service:1766 - _init_cluster | Request Id: 330dce53-fd0b-4bcd-9eb6-31bc23cd185f | ERROR :: Error executing script in node mstr-aek8: <module 'container_service_e                                                xtension.exceptions' from '/usr/local/lib/python3.8/dist-packages/container_service_extension/exceptions.py'>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/container_service_extension/def_/cluster_service.py", line 1873, in _execute_script_in_nodes
    _wait_until_ready_to_exec(vs, vm, password)
  File "/usr/local/lib/python3.8/dist-packages/container_service_extension/def_/cluster_service.py", line 1832, in _wait_until_ready_to_exec
    result = vs.execute_script_in_guest(
  File "/usr/local/lib/python3.8/dist-packages/vsphere_guest_run/vsphere.py", line 203, in execute_script_in_guest
    self.upload_file_to_guest(vm, user, password, content, target)
  File "/usr/local/lib/python3.8/dist-packages/vsphere_guest_run/vsphere.py", line 137, in upload_file_to_guest
    url = content.guestOperationsManager.fileManager. \
  File "/usr/local/lib/python3.8/dist-packages/pyVmomi/VmomiSupport.py", line 706, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pyVmomi/VmomiSupport.py", line 512, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/usr/local/lib/python3.8/dist-packages/pyVmomi/SoapAdapter.py", line 1397, in InvokeMethod
    raise obj # pylint: disable-msg=E0702
pyVmomi.VmomiSupport.vmodl.fault.SystemError: (vmodl.fault.SystemError) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'A general system error occurred: vix error codes = (3016, 0).\n',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   reason = 'vix error codes = (3016, 0).\n'
}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/container_service_extension/def_/cluster_service.py", line 1756, in _init_cluster
    result = _execute_script_in_nodes(sysadmin_client, vapp=vapp,
  File "/usr/local/lib/python3.8/dist-packages/container_service_extension/def_/cluster_service.py", line 1900, in _execute_script_in_nodes
    raise e.ScriptExecutionError(f"Error executing script in node {node_name}: {str(e)}")  # noqa: E501
container_service_extension.exceptions.ScriptExecutionError: Error executing script in node mstr-aek8: <module 'container_service_extension.exceptions' from '/usr/local/lib/python3.8/dist-p                                                ackages/container_service_extension/exceptions.py'>
21-03-25 13:00:01 | cluster_service:644 - _create_cluster_async | Request Id: 330dce53-fd0b-4bcd-9eb6-31bc23cd185f | ERROR :: Error creating cluster 'cls1'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/container_service_extension/def_/cluster_service.py", line 1873, in _execute_script_in_nodes
    _wait_until_ready_to_exec(vs, vm, password)
  File "/usr/local/lib/python3.8/dist-packages/container_service_extension/def_/cluster_service.py", line 1832, in _wait_until_ready_to_exec
    result = vs.execute_script_in_guest(
  File "/usr/local/lib/python3.8/dist-packages/vsphere_guest_run/vsphere.py", line 203, in execute_script_in_guest
    self.upload_file_to_guest(vm, user, password, content, target)
  File "/usr/local/lib/python3.8/dist-packages/vsphere_guest_run/vsphere.py", line 137, in upload_file_to_guest
    url = content.guestOperationsManager.fileManager. \
  File "/usr/local/lib/python3.8/dist-packages/pyVmomi/VmomiSupport.py", line 706, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pyVmomi/VmomiSupport.py", line 512, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/usr/local/lib/python3.8/dist-packages/pyVmomi/SoapAdapter.py", line 1397, in InvokeMethod
    raise obj # pylint: disable-msg=E0702
pyVmomi.VmomiSupport.vmodl.fault.SystemError: (vmodl.fault.SystemError) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'A general system error occurred: vix error codes = (3016, 0).\n',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   reason = 'vix error codes = (3016, 0).\n'
}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/container_service_extension/def_/cluster_service.py", line 1756, in _init_cluster
    result = _execute_script_in_nodes(sysadmin_client, vapp=vapp,
  File "/usr/local/lib/python3.8/dist-packages/container_service_extension/def_/cluster_service.py", line 1900, in _execute_script_in_nodes
    raise e.ScriptExecutionError(f"Error executing script in node {node_name}: {str(e)}")  # noqa: E501
container_service_extension.exceptions.ScriptExecutionError: Error executing script in node mstr-aek8: <module 'container_service_extension.exceptions' from '/usr/local/lib/python3.8/dist-p                                                ackages/container_service_extension/exceptions.py'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/container_service_extension/def_/cluster_service.py", line 560, in _create_cluster_async
    _init_cluster(self.context.sysadmin_client,
  File "/usr/local/lib/python3.8/dist-packages/container_service_extension/def_/cluster_service.py", line 1767, in _init_cluster
    raise e.ClusterInitializationError(
container_service_extension.exceptions.ClusterInitializationError: Couldn't initialize cluster: Error executing script in node mstr-aek8: <module 'container_service_extension.exceptions' fr                                                om '/usr/local/lib/python3.8/dist-packages/container_service_extension/exceptions.py'>
21-03-25 13:00:01 | cluster_service:649 - _create_cluster_async | Request Id: 330dce53-fd0b-4bcd-9eb6-31bc23cd185f | INFO :: Error creating cluster 'cls1'. Deleting cluster (rollback=True)
21-03-25 13:00:01 | cluster_service:1485 - _delete_vapp | Request Id: 330dce53-fd0b-4bcd-9eb6-31bc23cd185f | DEBUG :: Deleting vapp cls1 in (org: 06300, vdc: vdc.06300)

**Comment by sahithi** [comment]
Below is the error causing the cluster initialization failure. We recommend retrying for this kind of error coming from the vSphere layer. Ensure there are no connectivity issues between the VM and vSphere.

_pyVmomi.VmomiSupport.vmodl.fault.SystemError: (vmodl.fault.SystemError) {
dynamicType = ,
dynamicProperty = (vmodl.DynamicProperty) [],
msg = 'A general system error occurred: vix error codes = (3016, 0).\n',
faultCause = ,
faultMessage = (vmodl.LocalizableMessage) [],
reason = 'vix error codes = (3016, 0).\n'
}_

**Comment by work423** [comment]
vCenter Server 6.7 Update 3g is in the same network.
Seems like this problem appears only with Ubuntu-16.04 (vm version 10) templates.
With PhotonOS (vm version 11) template cluster created successful

**Comment by work423** [comment]
After restart vcd CSE creates clusters.
